### ISSUE TITLE
Как использовать bem-lib-site?

### ISSUE THREAD

**Issue by ilyar** [bem/bem-forum-content-ru#1083]
@tadatuta рассказал как использовать [автоматическую генерацию актуальной документации для модульного фронтенда](https://youtu.be/kivLyXGJbis?t=18734), [презентация](https://tadatuta.github.io/lib-builder-talk-subbotnik-2016/). Осталось не понятно как это использовать. Покажите минимальный кейс использования [bem-lib-site](https://github.com/bem-site/bem-lib-site) и расскажите где читать про остальное.

**Comment by tadatuta** [comment]
Привет!

Пока почитать, к сожалению, негде — документация в процессе написания.

Минимальный кейс использования предполагается такой:
1. Поставить `bem-lib-site`
2. Создать конфиг `.bemrc`, в котором описать собираемую библиотеку ([пример](https://github.com/bem-site/bem-lib-site-data#library-config)).
3. Вызвать бинарник `bem-lib-site` с указанием пути к собираемой библиотеке: `bem-lib-site bem-core`

Если ничего в процессе не взорвалось, то на выходе в папке, указанной в конфиге как `outputFolder` появится куча файлов, среди которых будут папки для каждого собираемого языка и в них папки с документацией по каждому блоку. Это дело должно быть можно открывать хоть с файловой системы, хоть паблишить на `gh-pages`.

Если что-то идет не так (а такое вполне возможно на данном этапе) — заводи issues, буду чинить.

**Comment by ilyar** [comment]
```bash
npm i -g bem-lib-site
cd docstest
cat .bemrc
```

```JavaScript
module.exports = {
    modules: {
        'bem-tools': {
            plugins: {}
        },
        'bem-lib-site-data': {
            tempFolder: 'tmp',
            outputFolder: 'output',
            langs: ['ru', 'en'],
            platforms: { // TODO: make it really optional
                'desktop': ['common', 'deskpad', 'desktop'],
                'touch-phone': ['common', 'touch', 'touch-phone'],
                'touch-pad': ['common', 'deskpad', 'touch', 'touch-pad']
            },
            libs: {
                'bem-components': {
                    langs: ['ru', 'en'],
                    github: {
                        url: 'github.com',
                        user: 'bem',
                        repo: 'bem-components',
                        defaultBranch: 'v3'
                    }
                }
            }
        }
    }
};
```

```bash
bem-lib-site .
TypeError: Cannot read property 'libs' of undefined
    at Object.<anonymous> (/home/ilyar/.nvm/versions/node/v5.5.0/lib/node_modules/bem-lib-site/node_modules/bem-lib-site-data/.enb/make.js:15:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at module.exports.inherit.init (/home/ilyar/.nvm/versions/node/v5.5.0/lib/node_modules/bem-lib-site/node_modules/enb/lib/make.js:90:17)
    at module.exports (/home/ilyar/.nvm/versions/node/v5.5.0/lib/node_modules/bem-lib-site/node_modules/enb-magic-platform/lib/apply.js:25:25)
    at Object.module.exports [as runTasks] (/home/ilyar/.nvm/versions/node/v5.5.0/lib/node_modules/bem-lib-site/node_modules/enb-magic-platform/lib/api/run-tasks.js:28:12)
```

Заводить issues или я неправильно понял?
Про `.bemrc` тоже еще ничего почитать?

**Comment by tadatuta** [comment]
Про `.bemrc` см. https://github.com/bem-sdk/bem-config и, если нужны подробности, https://github.com/tadatuta/betterc

На баг посмотрю, отпишусь, если что-то выясню.

**Comment by tadatuta** [comment]
@ilyar а что лежит в этот момент в `docstest`? если там пусто, то ничего сгенерироваться и не может. папка, на которую натравливается `bem-lib-site` обязана быть «полноценной» библиотекой блоков (у нее должен быть `package.json` с указанием имени и в конфиге `.bemrc` должно что-то про эту библиотеку.

**Comment by ilyar** [comment]
@tadatuta Папка действительно пуста  это воспроизводится по сценарию из [bem-lib-site#1](https://github.com/bem-site/bem-lib-site/issues/1). Осознав что папка должна быть полноценной получается такой кейс:
```bash
# 1. инструмент
npm i -g bem-lib-site

# 2. среда
rm -fr docstest && mkdir docstest && cd $_

# 3. проект
npm init -f

# 4. конфигурация
echo "module.exports = {
    'root': true,
    'levels': {
        'blocks': {
            'scheme': 'nested',
            'default': true
        }
    },
    modules: {
        'bem-tools': {
            plugins: {}
        },
        'bem-lib-site-data': {
            tempFolder: 'tmp',
            outputFolder: 'distr/docs',
            langs: ['ru', 'en'],
        }
    }
};" | tee .bemrc

# 5. папки
mkdir -p blocks/b1 distr/docs

# 6. файлы
echo "# Block b1" | tee blocks/b1/b1.{en,ru}.md
echo ".b1 {}" | tee blocks/b1/b1.css

# 7. проверяем всели на месте
tree
.
├── blocks
│   └── b1
│       ├── b1.css
│       ├── b1.en.md
│       └── b1.ru.md
├── distr
│   └── docs
│       └── data
└── package.json

5 directories, 4 files

# 8. генерация документации
bem-lib-site .
/home/user/.nvm/versions/node/v5.5.0/lib/node_modules/bem-lib-site/node_modules/bem-lib-site-data/index.js:36
    process.env.BEM_TEMPLATE_ENGINE = libConfig.templateEngine || config.templateEngine;
                                               ^

TypeError: Cannot read property 'templateEngine' of undefined
    at module.exports (/home/user/.nvm/versions/node/v5.5.0/lib/node_modules/bem-lib-site/node_modules/bem-lib-site-data/index.js:36:48)
    at module.exports (/home/user/.nvm/versions/node/v5.5.0/lib/node_modules/bem-lib-site/index.js:10:12)
    at Object.<anonymous> (/home/user/.nvm/versions/node/v5.5.0/lib/node_modules/bem-lib-site/bin/bem-lib-site:3:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

Что дорожно быть в `templateEngine`?

**Comment by tadatuta** [comment]
На самом деле `libConfig` должен быть объектом, а если templateEngine не окажется, то там сработает фоллбек. Оно сейчас падает, т.к. не намайнился конфиг для либы.

Но в такой постановке проблема понятна, я добавлю еще фоллбеков, чтобы оно могло либо что-то осмысленное в консоль писать, либо даже какой-то полезный результат генерить.

Кроме того я начал пилить тесты, так что будет что использовать в качестве примера.

**Comment by ilyar** [comment]
может как нибудь помочь?

**Comment by ilyar** [comment]
Работает если в конфиг добавить:
```JavaScript
            libs: {
                docstest: {
                    templateEngine: '',
                },
            },
```

в итоге:
```bash
# 4. конфигурация
echo "module.exports = {
    'root': true,
    'levels': {
        'blocks': {
            'scheme': 'nested',
            'default': true
        }
    },
    modules: {
        'bem-tools': {
            plugins: {}
        },
        'bem-lib-site-data': {
            tempFolder: 'tmp',
            outputFolder: 'distr/docs',
            langs: ['ru', 'en'],
            libs: {
                docstest: {
                    templateEngine: '',
                },
            },
        }
    }
};" | tee .bemrc
```

**Comment by ilyar** [comment]
@tadatuta

При повторном запуске  `bem-lib-site .` получаю ошибку:

```bash
Error: Cannot delete files/folders outside the current working directory. Can be overriden with the `force` option.
    at safeCheck (/home/user/.nvm/versions/node/v5.5.0/lib/node_modules/bem-lib-site/node_modules/del/index.js:19:9)
    at /home/user/.nvm/versions/node/v5.5.0/lib/node_modules/bem-lib-site/node_modules/del/index.js:35:5
    at Array.map (native)
    at /home/user/.nvm/versions/node/v5.5.0/lib/node_modules/bem-lib-site/node_modules/del/index.js:33:28
```
Вероятно тут https://github.com/bem-site/bem-lib-site-view/blob/ca3eebdd3cbec37e0d0614cc22b5686f3d1d99c7/index.js#L34 надо

```diff
-    return del(outputFolder).then(function() {
+    return del(outputFolder, { force : true }).then(function() {
```

Обходное решение:

```bash
# 8. генерация документации
rm -rf distr/docs/** && bem-lib-site .
```

**Comment by tadatuta** [comment]
Да, уже влили (см. https://github.com/bem-site/bem-lib-site-data/pull/10), но еще нет версии с правками.

**Comment by ilyar** [comment]
@tadatuta для ошибки:  "TypeError: Cannot read property 'templateEngine' of undefined" уже есть решение https://github.com/bem-site/bem-lib-site-data/commit/af09ab03060d739e9bf3abe9fcaf6d238aabcd9d надо только выпустить новую версию bem-lib-site-data и bem-lib-site https://github.com/bem-site/bem-lib-site/blob/master/package.json#L19

**Comment by tadatuta** [comment]
я хочу еще несколько фиксов сделать до выпуска

**Comment by ilyar** [comment]
Ясно, спасибо.

Есть еще один не понятный моменте, bem-lib-site генерирует следующие:

```bash
tree distr/docs/
distr/docs/
├── data
│   └── docstest
│       ├── bower.json
│       ├── data.json
│       └── desktop.docs
│           └── b1
│               ├── b1.bemdecl.js
│               ├── b1.data.json
│               ├── b1.en.doc.html
│               ├── b1.en.md
│               ├── b1.jsdoc.html
│               ├── b1.jsdoc.json
│               ├── b1.jsdoc.md
│               ├── b1.meta.json
│               ├── b1.ru.doc.html
│               ├── b1.ru.md
│               └── b1.source-files.json
└── docstest
    ├── en
    │   ├── desktop
    │   │   └── b1
    │   │       └── index.html
    │   ├── index.css
    │   └── index.js
    └── ru
        ├── desktop
        │   └── b1
        │       └── index.html
        ├── index.css
        └── index.js

11 directories, 19 files
```
Другими словами получаем страничку документации по каждому блоку.

@tadatuta Не хватает индекса, bem-lib-site это умеет или надо что-то придумывать? Пожалуйста подскажи, как это можно сделать.

**Comment by tadatuta** [comment]
По задумке индексом должен быть отрендеренный README[.lang].md из корня библиотеки, но сейчас это не реализовано.

**Comment by ilyar** [comment]
Понял, спасибо.

Выражу личное мнение, думаю, будет удобно следующие поведение:

- язык документации по умолчанию (когда в конфиге отсутствует `langs`) , данные для него будут браться из файла технологии без суффикса т.е. `project/blocks/b1/b1.md` и project `project/readme.md`;
- `readme.md` из корня библиотеки должен быть регистронезависимый;
- индекс документации это список блоков дополненный информацией из корневого `readme.md` это может быть опциональным поведением.


Еще уточнение по использованию, каким образом на данный момент можно вмешаться в формирование конечного результата? Хочу добавить индекс.

**Comment by vithar** [comment]
Я в процессе фикса индекса, changelog и migration для библиотеки

**Comment by tadatuta** [comment]
@ilyar можно заводить issues в соответствующих репозиториях и после обсуждения брать в работу, если есть желание/возможность. буду очень благодарен!

**Comment by ilyar** [comment]
https://github.com/bem-site/bem-lib-site-data/issues/13
https://github.com/bem-site/bem-lib-site-data/issues/14
https://github.com/bem-site/bem-lib-site-view/issues/11

**Comment by kmadorin** [comment]
Повторил все шаги выше. Но выдается ошибка Cannot read property 'outputFolder' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/bem-lib-site/node_modules/bem-lib-site-view/lib/process-blocks.js:14:26).

.bemrc в корне проекта лежит, все ок. Может изменился способ задания конфига?

**Comment by kompolom** [comment]
Очень уж хочется попробовать, но за два подхода тулза не взлетела...

**Comment by ilyar** [comment]
@kompolom @kmadorin

```bash
git clone git@github.com:ilyar/bem-lib-site-test.git
cd bem-lib-site-test && npm install
npm test
open docs/index.html
```

Работает, [хак внутри](https://github.com/ilyar/bem-lib-site-test/blob/master/package.json#L10) (может быть он уже не нужен).

**Comment by ilyar** [comment]
Сборку можно посмотреть тут [ilyar.github.io/bem-lib-site-test/](https://ilyar.github.io/bem-lib-site-test/).

**Comment by kompolom** [comment]
@ilyar, Спасибо за демку, завелось наконец-то! У меня только jsdoc собрался. md файлы не подключились.

**Comment by kompolom** [comment]
@ilyar Попробовал снова собрать доки. Все сломалось!

**Comment by kompolom** [comment]
```
Data was collected at /home/jenik/myprojects/bem-lib-site-test/docs/data/.-
module.js:327
    throw err;
    ^

Error: Cannot find module '/home/jenik/myprojects/bem-lib-site-test/docs/data/data'
```

**Comment by Realetive** [comment]
@kompolom, у меня тоже сборка развалилась после обновления на `bem-core#v4`.
Сегодня @tadatuta в Телеграмме говорил, что там пока много «ненадёжностей» и грозился в ближайшее время (сегодня) «влить туда пачку фиксов и в перспективе планируют переводить на v4».

**Comment by vithar** [comment]
Посмотрите внимательно на .bemrc, там изменился формат.

Сейчас так:

```
module.exports = {
    root: true,

    modules: {
        'bem-lib-site': {
            langs: ['uk', 'ru', 'en'],

            data: {
                tempFolder: 'tmp',
                outputFolder: '.cache/bem-lib-site-data'
            },
            view: {
                outputFolder: 'bem-lib-site-view-output'
            },
            platforms: { // TODO: make it really optional
                'desktop': ['common', 'deskpad', 'desktop', 'test'],
                'touch-phone': ['common', 'touch', 'touch-phone', 'test'],
                'touch-pad': ['common', 'deskpad', 'touch', 'touch-pad', 'test']
            },
            libs: {
                'bem-components': {
                    langs: ['uk', 'ru', 'en'],
                    github: {
                        url: 'github.com',
                        user: 'bem',
                        repo: 'bem-components',
                        defaultBranch: 'v3.0.0'
                    }
                }
            }
        }
    }
};
```

**Comment by vithar** [comment]
Может в этом дело.

**Comment by kompolom** [comment]
Была бы хоть какая то документация что в конфиге писать куда и зачем...

**Comment by kompolom** [comment]
@vithar Вот сгенерировал я данные в папку
` cache/bem-lib-site-data`
запускаю `bem-lib-site-view cache`
и получаю:

```
module.js:327
    throw err;
    ^

Error: Cannot find module '/home/jenik/myprojects/ap-components/cache/data'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (/home/jenik/myprojects/ap-components/node_modules/bem-lib-site-view/lib/prepare-data.js:27:19)
    at module.exports (/home/jenik/myprojects/ap-components/node_modules/bem-lib-site-view/index.js:21:16)
    at Object.<anonymous> (/home/jenik/myprojects/ap-components/node_modules/bem-lib-site-view/bin/bem-lib-site-view:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```
Никак не пойму что за модуль оно там найти хочет.

**Comment by vithar** [comment]
Оно ищет data.json.

Так должно работать: `bem-lib-site-view cache/bem-lib-site-data/ap-components-1.1.0`

**Comment by ilyar** [comment]
@kompolom @Realetive @vithar во всем виноват этот коммит https://github.com/bem-site/bem-lib-site-data/commit/1c7f630f3193990ee14bc2dc386b6b896f24e232

**Comment by kompolom** [comment]
@ilyar Виноват, но не во всем
```
bem-lib-site-view cache/bem-lib-site-data/ap-components-1.1.0/
[TypeError: Path must be a string. Received undefined]
```

**Comment by ilyar** [comment]
Согласен, поторопился с выводами, проблема фиксится так:  https://github.com/ilyar/bem-lib-site-test/commit/c77da0d174e1c45a2c0a3e29e9da224f25271937

Обновленное демо https://ilyar.github.io/bem-lib-site-test/ и о счастье маркдаун теперь рендерится! 

@vithar спасибо за обновление.

**Comment by ilyar** [comment]
Все таки пришлось откатить bem-site/bem-lib-site-data до 7f13647f теперь [![Build Status](https://travis-ci.org/ilyar/bem-lib-site-test.svg?branch=master)](https://travis-ci.org/ilyar/bem-lib-site-test) на мастере валится https://travis-ci.org/ilyar/bem-lib-site-test/jobs/183339355#L1298

Пока оставлю так.

**Comment by tadatuta** [comment]
Ребята, спасибо, что вы все это терпите.
Мы сегодня в очередной раз не успели, но у нас действительно большая пачка правок лежит локально. Нужно разобрать по коммитам и запушить.
Впрочем, даже после влития считать bem-lib-site стабильным будет преждевременно.

**Comment by kompolom** [comment]
Ждем с нетерпением

**Comment by lilliputten** [comment]
Добрался до попыток привинчивания bem-lib-site. Третий день экспериментов с практически нулевым результатом.

Использовал в качестве отправной точки [bem-lib-site-test](https://github.com/ilyar/bem-lib-site-test/). Получается, что без изменений либо кода пакетов (`bem-lib-site*`), либо имеющегося в репозитории конфига, ничего вообще не работает.

Старался обходиться минимальными правками и только в конфиге (хотя по началу делал всякие допроверки вроде `( libConfig && libConfig.templateEngine ) || config.templateEngine` или `config.libs && config.libs[lib] || {}`, потом вроде научился обходиться добавлением параметров конфига. (В общем, самое безобразное, что к имеющимся модулям не прилагается внятного how-to или примера _рабочего_ конфига.)

Прошу помочь с настройкой или ткнуть в рабочий кейс или _правильный_ образец `.bemrc` для старта.

Сейчас `bem-lib-size .` проходит без ошибок, на выходе получаю два файла (`find out -type f`):
``` shell
out/data/index.css
out/data/index.js
```
При этом в папке `~/npm/node_modules/bem-lib-site/node_modules/bem-lib-site-data/tmp/data/desktop.docs/b1/` получаю набор файлов:
``` shell
b1.bemdecl.js
b1.data.json
b1.en.md
b1.en.doc.html
b1.jsdoc.html
b1.jsdoc.json
b1.jsdoc.md
b1.meta.json
b1.ru.md
b1.ru.doc.html
```
-- в котором все `*.{html,md}` файлы пустые.

Также создаётся файл `~/npm/node_modules/bem-lib-site/node_modules/bem-lib-site-data/out/data/data/readme.md` с копией README из самого `bem-lib-site-data`.

Конфиг сейчас (в последних экспериментах) такой:
``` javascript
module.exports = {
    root : true,
    levels : {
        'blocks' : {
            scheme : 'nested',
            default : true,
        },
    },
    modules : {
        'bem-lib-site-data' : {
            tempFolder : 'out/temp',
            outputFolder : 'out/data',
            libs : {
                '.' : {
                    templateEngine : 'BEMHTML',
                },
            },
        },
    },
};
```

Вывод команды `bem-lib-site .`:
```
16:28:37.113 - build started
16:28:37.159 - [rebuild] [tmp\data\desktop.docs\b1\b1.bemdecl.js] file-provider
16:28:37.159 - [rebuild] [tmp\data\desktop.docs\b1\b1.levels] levels
16:28:37.159 - [rebuild] [tmp\data\desktop.docs\b1\b1.files] files
16:28:37.175 - [rebuild] [tmp\data\desktop.docs\b1\b1.dirs] files
16:28:37.175 - [rebuild] [tmp\data\desktop.docs\b1\b1.meta.json] meta-json
16:28:37.191 - [rebuild] [tmp\data\desktop.docs\b1\b1.ru.doc.html] doc-html-i18n
16:28:37.191 - [rebuild] [tmp\data\desktop.docs\b1\b1.en.doc.html] doc-html-i18n
16:28:37.191 - [rebuild] [tmp\data\desktop.docs\b1\b1.en.md] md-i18n
16:28:37.191 - [rebuild] [tmp\data\desktop.docs\b1\b1.ru.md] md-i18n
16:28:37.191 - [rebuild] [tmp\data\desktop.docs\b1\b1.jsdoc.json] jsdoc-json
16:28:37.206 - [rebuild] [tmp\data\desktop.docs\b1\b1.jsdoc.md] jsdoc-to-md
16:28:37.206 - [rebuild] [tmp\data\desktop.docs\b1\b1.data.json] data-json
16:28:37.222 - [rebuild] [tmp\data\desktop.docs\b1\b1.jsdoc.html] html-from-md
16:28:37.222 - build finished - 1077ms
Data was collected at {...}\out\data\data
```
Тестируется на Windows7, node@v6.10.0.

bem-lib-site установлен глобально:
```
`-- bem-lib-site@0.1.2
  +-- bem-lib-site-data@0.0.7
  `-- bem-lib-site-view@0.0.5
```

**Comment by ilyar** [comment]
Сумбурно как то, давай по порядку, что из этого сценария не работает?

    git clone git@github.com:ilyar/bem-lib-site-test.git
    cd bem-lib-site-test && npm install
    npm test
    open docs/index.html

**Comment by lilliputten** [comment]
@ilyar Это работает, спасибо. Раньше пробовал в основном через `bem-lib-site`. Это, видимо, какая-то проблема с установкой `bem-lib-site-view` в автоматическом режиме?

Попробую плясать от этой конфигурации.

Чуть вопросов:

- Реально ли поключить генерацию документации в конфиг enb make, чтобы прокидывать туда общую конфигурацию? Наверное, могу за основу взять тот же `bem-site-lib` гриненковский?

- Есть ли возможность подключать свои плагины -- по аналогии с jsdoc? (Напр., для предпарсинга/модификации описаний сущностей?) В конфиге видал опцию, но не видел рабочего примера? Есть ли что-то в опсианиях/кейсах?

**Comment by ilyar** [comment]
@tadatuta какие есть обновления по инструменту (где почитать)?

**Comment by ilyar** [comment]
актуальная теория https://yandex.ru/blog/x-plain/materily-mini-giperbatona-pro-dokumentatsiyu-v-markdown

https://www.youtube.com/watch?v=ifydjGoDMU4

https://www.youtube.com/watch?v=mJ5IqzmXuMo

**Comment by lilliputten** [comment]
Подскажите, изменилась ли ситуаиция за прошедшее время? Или так же надо использовать бубны для запуска докогенератора?

Собственные эксперименты лежат до сих в наполовину рабочем виде, к рабочим проектам подключать так пока руки не дошли. Сейчас начинать с них? Или можно попробовать какой-то более гуманный способ? (Наск. помню, были ещё доп. сложности из-за моего не оч. стандартного способа хранения блоков в проекте...)

**Comment by qfox** [comment]
Привет.

Я не знаю судьбу bem-lib-site-data, но мы сейчас пробуем с другой стороны зайти к снаряду в https://github.com/agrarium/agrarium

Это прототип, но нам нравится как идут дела.
У нас там многослойная схема с адаптерами-трансформерами, которая на выходе должна давать сводную информацию о нужных компонентах.

Пока не нравится, что нет толковых парсеров для кода и jsdoc, и много руками надо будет писать) Но это лирика.
Сейчас собираем тесткейсы для парсинга js и jsdoc, в планах придумать API для плогинов.
