### ISSUE TITLE
К

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-forum-content-ru#191]

**Comment by tadatuta** [comment]
@zxqfox 
`vi .../users-list.bemhtml.js +501`
найти переменную рядом с [0], если этого уже не достаточно, подняться чуть выше — выяснить, в каком блоке проблема.

piece of cake ;)

**Comment by apsavin** [comment]
Вообще, если собирать xjst в dev-режиме, то дебажить намного проще. И sourcemaps создать проблемой не должно быть.

**Comment by zxqfox** [comment]
@apsavin Ммм, да. Я почему-то решил, что YENV все заруливает...

@tadatuta А что ты думаешь про добавить в генератор/бем-стаб проверку на `!isProd` к `BEM*_ENV`?

**Comment by tadatuta** [comment]
@zxqfox я даже в девелопменте обычно собираю шаблоны в продакшен-режиме и переключаюсь на devMode только когда нужно подебажить что-то сложное, поэтому скорее против. но если ты пишешь какой-то динамический проект, предложу использовать `nodemon` и задавать переменные окружения через его конфиг — тогда ты не завязан на умолчания.

**Comment by zxqfox** [comment]
@tadatuta тогда я категорически за sourcemaps ;-) на морде тоже пригодится, в т.ч. при сборке в prod режиме

**Comment by tadatuta** [comment]
@zxqfox мы все за sourcemaps, но как раз для production-режима запилить их не так-то просто

**Comment by zxqfox** [comment]
@tadatuta А issue уже стоит? Там неоднозначность, конечно ;-(

![image](https://cloud.githubusercontent.com/assets/677518/5987433/bb36709c-a93a-11e4-99b1-49ae9116fb87.png)

Были бы тесткейсы с пониманием чо куда резолвить ;-)

**Comment by tadatuta** [comment]
@zxqfox есть вот [такое](https://github.com/bem/bem-xjst/issues/19)

А про честные сорсмапы в пост призываются @indutny и @vkz

**Comment by voischev** [comment]
:+1:  Дебажиться ок. Но конечно можно улучшить этот момент ;)

**Comment by sefus** [comment]
А если ошибка в bemjson?
```
SyntaxError: Unexpected token {
    at exports.techMixin.getCreateResult (/home/vagrant/bem/test-project/node_modules/bem/lib/techs/v2/bemdecl.js.js:18:37)
    at /home/vagrant/bem/test-project/node_modules/bem/lib/tech/v2.js:120:41
    at Array.map (native)
    at exports.Tech.INHERIT.getCreateResults (/home/vagrant/bem/test-project/node_modules/bem/lib/tech/v2.js:119:47)
    at exports.Tech.INHERIT.create (/home/vagrant/bem/test-project/node_modules/bem/lib/tech/v2.js:90:57)
    at exports.Tech.INHERIT.createByDecl (/home/vagrant/bem/test-project/node_modules/bem/lib/tech/v2.js:77:25)
    at /home/vagrant/bem/test-project/node_modules/bem/lib/commands/create.js:118:51
    at Array.map (native)
    at /home/vagrant/bem/test-project/node_modules/bem/lib/commands/create.js:117:40
    at Array.map (native)
    at Cmd. (/home/vagrant/bem/test-project/node_modules/bem/lib/commands/create.js:116:32)
    at /home/vagrant/bem/test-project/node_modules/bem/node_modules/coa/lib/cmd.js:483:22
    at _fulfilled (/home/vagrant/bem/test-project/node_modules/bem/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/home/vagrant/bem/test-project/node_modules/bem/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/home/vagrant/bem/test-project/node_modules/bem/node_modules/q/q.js:760:13)
    at /home/vagrant/bem/test-project/node_modules/bem/node_modules/q/q.js:574:44
    at flush (/home/vagrant/bem/test-project/node_modules/bem/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)
```
Не указан даже файл в котором ошибка, не то что номер строки. Пропустил запятую и вынужден вчитываться в каждую строчку. Нет ли какого-то валидатора?

**Comment by tadatuta** [comment]
@sefus BEMJSON — это самый обычный JS, поэтому его валидировать можно любым валидатором JS от jslint/jshint до подсветки в IDE и запуска в консоли:

```bash
node -e "require('./desktop.bundles/index/index.bemjson.js')"

/Users/tadatuta/Sites/pr-stub-update/desktop.bundles/index/index.bemjson.js:12
    content : [
    ^^^^^^^
SyntaxError: Unexpected identifier
```

**Comment by zxqfox** [comment]
`node -e "require('...` ? Мусье знает толк... ;-) есть еще тема:
```
sh -c "node -e "\""require('child_process').execFile('node', ['-e', 'require(\'./index.bemjson.js\')'], console.log);\""
```

**Comment by sefus** [comment]
@tadatuta спасибо, node поможет. По крайней мере пока я  правлю один файл.

**Comment by zxqfox** [comment]
@sefus Если sublime2,3 — то https://github.com/SublimeLinter/SublimeLinter3 + https://github.com/SublimeLinter/SublimeLinter-jshint
