### ISSUE TITLE
Использование BH вместо BEMHTML

### ISSUE THREAD

**Issue by belozyorcev** [bem/bem-forum-content-ru#236]
Добрый день. 

:)

А что нужно для того, чтобы вместо ```bemhtml``` использовать ```bh``` ?

П.Н.
```bh``` мне показался более наглядным и привычным, в сравнении с ```bemhtml```. Вдобавок ко всему он ещё и быстрее.

**Comment by Guria** [comment]
Абсолютно тоже самое - просто начать пользоваться. В bem-stub и generator-bem-stub должно быть всё настроено для использования BH

**Comment by Guria** [comment]
Конфиг из ветки `bh` собственно можно попробовать взять https://github.com/bem/project-stub/blob/bh/.enb/make.js

**Comment by belozyorcev** [comment]
@guria т.е. никаких дополнительных настроек не нужно? Как он bem-stub определит, что я хочу использовать bh ?

**Comment by Guria** [comment]
Нужно исправить конфиг, см. выше.
@andrewblond конфиг актуальный? на сколько актуальна ветка bh?

**Comment by Guria** [comment]
@belozyorcev Ещё убедиться что установлены npm модули bh и enb-bh

**Comment by belozyorcev** [comment]
Вроде как удалось подключить. А файлы ```bh``` должны оканчиваться ```.bh.js```?

И по использованию вопрос :)
Наш шаблон блока должены выглядить таким сопособом?
```
var bh = new (require('bh').BH);
bh.match('button', function(ctx) {
    ctx.tag('button');
})
bh.processBemJson({ block: 'button' }); // { block: 'button', mods: {}, tag: 'button' }
bh.apply({ block: 'button' }); // '<button class="button"></button>'
```

**Comment by sipayRT** [comment]
В [bem-components](https://github.com/bem/bem-components) поддерживаются оба шаблонизатора, там куча примеров. Например, https://github.com/bem/bem-components/blob/v2/common.blocks/button/button.bh.js

**Comment by zxqfox** [comment]
@belozyorcev В шаблоне блока достаточно так:
```
module.exports = function (bh) {
    bh.match('button', function(ctx) {
        ctx.tag('button');
    });
};
```

Блок с `processBemJson` явно не нужен, 
```js
bh.processBemJson({ block: 'button' }); // { block: 'button', mods: {}, tag: 'button' }
```

Блок с apply явно тоже не нужно указывать, если сборку делаете enb/bem-tools
```js
bh.apply({ block: 'button' }); 
```
Либо нужен при выводе, чтобы туда засунуть готовый bemjson объект.
Можно сегенрировать stub (`yo bem-stub`) и собрать бандл, в нем будем `index.bh.js` — это будет пример сборки.

На счет скорости — спорный вопрос. Скорость сборки разная, размеры разные, синтаксис разный, скорость работы — ± одинаковая.

**Comment by tadatuta** [comment]
мы [договорились](https://github.com/bem/bem-components/issues/1286) отказаться от обертки `module.exports`

**Comment by zxqfox** [comment]
@tadatuta Молодцы ;-)

**Comment by belozyorcev** [comment]
Перевёл шаблоны на bh. Не сильно много пришлось править :-)

@tadatuta сейчас обёртка ещё нужна?

**Comment by tadatuta** [comment]
@belozyorcev нет

**Comment by belozyorcev** [comment]
@tadatuta а как будет выглядить без обёртки шаблон?

```
module.exports = function (bh) {

bh.match('b-map-filters', function (ctx, json) {
    ctx.content('привет');
});

}
```

**Comment by tadatuta** [comment]
```js
bh.match('b-map-filters', function (ctx, json) { // btw, если json не используется, его можно тоже не писать
    ctx.content('привет');
});
```

**Comment by belozyorcev** [comment]
@tadatuta параметр json используется для получения базового контента из bemjson.
Я так понимаю, что json и ctx похожи, только ctx - предоставляет более безопасную работу с json?

А вот по поводу обёртки - ошибка

```
// module.exports = function (bh) {

bh.match('b-map-filters', function (ctx, json) {
    ctx.content('привет');
});

// }
```

```
ReferenceError: bh is not defined
   at Object.<anonymous> (/home/sergey/projects/soprof-bem/desktop.blocks/b-map-filters/b-map-filters.bh.js:3:1)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous> (/home/sergey/projects/soprof-bem/desktop.bundles/index-page/index-page.bh.js:34:1)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10) 
```

**Comment by apsavin** [comment]
@belozyorcev @tadatuta выше же по ссылке сказано что только в следующей версии отказ от обертки.

**Comment by tadatuta** [comment]
@belozyorcev видимо используется технология `bh-server`.
чтобы заработало, нужно в `.enb/make.js` вместо чего-то типа
```js
bh: require('enb-bh/techs/bh-server')
```

сделать
```js
bh: require('enb-bh/techs/bh-server-include')
```

**Comment by zxqfox** [comment]
@apsavin Это все магнитные бури и вспушки на солнышке.

**Comment by tadatuta** [comment]
@apsavin это в смысле, что мы в `bem-components` оторвем обертки в `v3`, а у себя на проектах так писать можно изначально

**Comment by belozyorcev** [comment]
@tadatuta всё заработало, спасибо :)

@apsavin у меня часть блоков в обёртке сейчас и ничего не конфликтует

**Comment by apsavin** [comment]
Хм, если не конфликтует - тогда не понятно, что это изменение ломает.

**Comment by zxqfox** [comment]
@apsavin Если только требует замены технологии в проектах с `bh-server` на `bh-server-include`, а, соотв., такое можно только в минорных, а лучше в мажорных релизах.

**Comment by apsavin** [comment]
О да, слона не приметил.

**Comment by zxqfox** [comment]
Это все эти самые бури и вспушки ;-)

**Comment by 4ok** [comment]
По мне так, bemhtml более интересен и и не стоит переходить на bh. Прозрачность - брось, шаблоны на bemhtml более прозрачные, если уметь готовить. Переход bemtools -> enb - да, здорово, только за!

Думаю за enb + bemhtml будущее, если конечно bemhtml будет развиваться, за enb таких беспокойств нет, хотя bemtools тоже не плох, все можно сделать и на нем, имея ввиду сборку технологий не приплетая лишнего.

**Comment by 4ok** [comment]
И еще хочется поинтересоваться - почему в последнее время на форуме нет ответов одних из главных борцов за БЭМ, Виталика и Вегета. Неужели им уже это все не интересно. Я не сомнено очень доволен ответами Владимира, но хотелось бы слышать мнения и других родоначальников технологии.

**Comment by belozyorcev** [comment]
@4ok всё везде прозрачно, когда уметь правильно готовить :) bh мне сейчас кажется более "привычным"

**Comment by tadatuta** [comment]
> почему в последнее время на форуме нет ответов одних из главных борцов за БЭМ, Виталика и Вегета. Неужели им уже это все не интересно.

Конечно, им интересно!
Проверить просто: https://github.com/veged?tab=activity
А Виталя сейчас готовит доклад про БЭМ на CodeFest ;)

// cc @veged @vithar

**Comment by veged** [comment]
@4ok мы тут ;-) просто не на всё хватает сил :-(

**Comment by belozyorcev** [comment]
@veged а можно узнать конкретно почему? На примере. (а то всё так абстрактно. Мол на BEMHTML можно делать такие вещи... Что BH отдыхает). 
Я сам всё больше начинаю любить BH, т.к. синтаксис кажется проще.

Возможно работал бы в BEMHTML - привыкал бы к нему и не нужен был бы BH.

**Comment by verybigman** [comment]
Я вот тоже навые проекты делаю на BH. Кажется удобнее и быстрее.

**Comment by dab** [comment]
@belozyorcev  `BEMHTML` и `BH` — декларативные шаблонизаторы. Оба используют js-синтаксис. Позволяют доопределять шаблоны. Вопрос синтаксиса — дело привычки и вкуса. 

На счет больших возможностей — в `BEMHTML` есть как минимум две части, которые отсутствуют в `BH`:
  — `BEMHTML` позволяет использовать в качестве подпредикатов любые JavaScript выражения. В `BH` — вы можете использовать только строки
  — В `BEMHTML` можно использовать [кастомные моды](https://ru.bem.info/technology/bemhtml/v2/templating/#Мода-4), в `BH` такого понятия как `мода` — нет
  — сюда же можно добавить возможность использовать на проекте `BEMHTML` совместно с `BEMTREE`

Для чего может понадобиться возможность использовать кастомные моды? В любой ситуации, когда надо обработать блок своим, «пользовательским», способом. Например когда в содержимом блока лежит много всего, а нам нужно точечно переопределять лишь какую-то часть, то ее можно вынести в отдельную моду:

```js
block('bla')(
    mode('url')('http://site.com'),
    content()(function() {
        return [
            // много всего,
            apply('url'),
            // еще много всего
        ];
    })
);
```

Теперь можно использовать моду `url` на уровне проекта,  вместо перекрывания всего содержимого:

```js
block('bla').mode('url')('http://new.com/');
```

Эти возможности накладывают и некоторые ограничения — нужно вдумчиво их использовать, чтобы не «прострелить себе ногу».

Различия по скорости совсем не такие, как казалось раньше. @mishanga проводил тестирование на реальном проекте, которое показало, что **BEMHTML не медленный**. 

Вывод: вы можете смело использовать на своем проекте `BH`, если указанные пункты для вас не имеют значения. Обратное тоже верно.

**Comment by belozyorcev** [comment]
@dab а как именно можно получить прострел в ногу?

**Comment by tadatuta** [comment]
@belozyorcev речь о том, что переусложнение шаблонов только потому, что есть такая возможность — это тоже плохо. в идеале шаблоны должны быть простыми.
