### ISSUE TITLE
Правильно собрать проект (enb)

### ISSUE THREAD

**Issue by Rahnar** [bem/bem-forum-content-ru#277]
Привет, друзья! Вот и закончил я свой сайт,  по технологии БЭМ. И мне не хватает последнего - это собрать проект. Я в корни не понимаю как это сделать, где можно почитать , как правильно это делать?
Что собственно делал я, я ввел такую команду (node_modules/.bin/enb make) он чет насобирал там и выдал что финиш, но где исходные файлы , которые он якобы собрал, я не могу найти...Куда он их вообще складывает?
Есть еще ряд вопросов , а именно:

1) Использовал я project-stub, где выбрал  не bem-tools,  а enb. Но , запуск сервера  почему-то,  по команде  npm-start не происходит, а только по bem-server. Почему так?Или так и должно быть?

2) Правильно ли я делал , что складывал картинки непосредственно в папку с сущностями ? Например __item и там лежат картинки  , сборщик потом сам мне закинет все картинки в папку img и пути поменяет в коде?

3) Теперь вопрос о сторонних папках. Я создал в корневой папке проекта  , папку со шрифтами , и от туда их подключаю, верно ли так поступать?А если мне понадобится какой-нибудь jquery плагин , который я хочу выкачивать  с бовера, мне надо будет создать  папку bower_components в самом проекте,  на одном уровне с папками common.blocks, libs и т.д ?
P.S: Вопрос о сборке , особой важности.. Спасибо!

**Comment by tadatuta** [comment]
@Rahnar 

> Куда он их вообще складывает?

В `desktop.bundles/index/*`.

> 1) Использовал я project-stub, где выбрал не bem-tools, а enb. Но , запуск сервера почему-то, по команде npm-start не происходит, а только по bem-server. Почему так?Или так и должно быть?

Не должно быть. Точно ли используется актуальная версия `project-stub`?

> 2) Правильно ли я делал , что складывал картинки непосредственно в папку с сущностями ? Например __item и там лежат картинки , сборщик потом сам мне закинет все картинки в папку img и пути поменяет в коде?

Да, для этого достаточно положить в корень проекта файл `.borschik` (именно с точкой в начале имени) с таким содержанием:
```js
{
    "freeze_paths" : {
        "libs/**": "img/",
        "*.blocks/**": "img/"
    }
}
```

> создал в корневой папке проекта , папку со шрифтами , и от туда их подключаю, верно ли так поступать?

Шрифты можно класть в папку с сущностями по аналогии с картинками, `borschik` сохранит пути.
Для работы с кастомными шрифтами удобно завести блока `font` с модификаторами `_face_my-font-family` для каждого конкретного шрифта и потом миксовать их к нужным блокам.

> если мне понадобится какой-нибудь jquery плагин, который я хочу выкачивать с бовера

`project-stub` поставляется с конфигом `bower`, где сказано, что пакеты нужно ставить в папку `libs` (и именно через `bower` ставятся `bem-core` и `bem-components`).
Так что потребуется добавить необходимые плагины в `bower.json`, сказать `bower i` и они встанут в `libs`.
Далее их можно подключать по-разному, но я бы рекомендова использовать такой подход:
1. Создать БЭМ-блок в качестве обертки над jQuery-плагином.
2. Задеклалирвать его как обычный `ym`-модуль:
```js
modules.define('my-plugin', ['jquery'], function(provide, $) {

/*borschik:include:../../libs/my-plugin/my-plugin.js*/

provide($);

});
```

Подробнее про borschik include см. https://ru.bem.info/tools/optimizers/borschik/js-include/

**Comment by Rahnar** [comment]
@tadatuta
Спасибо , Владимир! По поводу project-stub, ставил командой yo bem-app

**Comment by tadatuta** [comment]
@Rahnar 
у генератора 19 версий вышло: https://github.com/bem/generator-bem-stub/releases

**Comment by Rahnar** [comment]
@tadatuta
Сделал как Вы сказали, все получилось. Единственное не получилось с папкой и картинками. Я создал файлик .borschik вставил туда то, что выше. И ничего не произошло..

**Comment by tadatuta** [comment]
Возможно, конфиг был сгенерирован не последней версией генератора?
Должно быть так:
https://github.com/bem/project-stub/blob/bem-core/.enb/make.js#L92-L94

**Comment by Rahnar** [comment]
@tadatuta 
Конфиг на последней версии, вообщем пришлось все руками делать в ручное. Это ужасно , если честно... У меня щас след проект и  там 15 страниц, делать по БЭМ буду. И тут уже там не прокатит... А как-нибудь можно собрать в таком порядке чтобы в итоге сложилось в папку build в ней  скрипты в  scripts , css  в папку с css.

**Comment by tadatuta** [comment]
@Rahnar вручную делать точно не стоит.
я помогу настроить сборку, но если не секрет, какую задачу решает перекладывание собранных css и js в отдельные папки, если их всего-то по одному файлу на выходе после сборки?

**Comment by Rahnar** [comment]
@tadatuta
У меня просто выхода не было, мне надо было быстренько показать директору, ему ждать меня и пока сборщик сделаю не хотелось. А вот по поводу складывания по папкам,  стили , скрипты и прочего. Это в общем товарищи из бэкенда условили ,  чтобы я им такую архитектуру из папок представил.Они хотят чтобы у них все по полочкам было.
Мне хотя бы понять как собрать фотки из сущностей в папочку img , потому что попытки мои , были безрезультатными.  Бог с ним,  с этой иерархией для скриптов и прочего.
 Еще есть такой вопросик:
1)  когда я создам страницу новую в desktop.bundles например contact - скрипты подключать из папки  index  ?
2) я когда открыл файлик _index.js там очень много чего написанно было, я так понимаю это для использования i-bem.js,  я пока его не использую , пишу на ваниле. Можно ли это как-то убрать , все что там написанно? Потому что там около 1000 или даже более строк лишнего кода. Хотя i-bem.js постараюсь разобрать в ближайшее время.
Собственно это единственное чего пока я не понял. Спасибо!

**Comment by Guria** [comment]
@Rahnar i-bem скорее всего тянется за счёт блока page и/или bemhtml шаблонов. Это можно попробовать исправить с помощью переопределения части блоков и их зависимостей. Кроме того, скорее всего в index.js также конкатенируется в начало модульная система ymodules, которая вам скорее всего пока не нужна. Для исправления этого понадобится правка конфига сборщика.

Для использования ангуляра надо просто попробовать начать его использовать. В БЭМ нет ничего, что мешает его использовать. Генератор для этого тоже не обязательно использовать.

Проще всего если вы выложите ваш проект с конфигами и минимальным примером того как вы создаёте страницы, чтобы можно было подсказать, что с этим сделать в вашем случае.

**Comment by Rahnar** [comment]
@Guria
Я скину проект - касаемо ангулара , но чуток позже, но скину обязательно.  Щас вот с картинками разберусь и все.

**Comment by tadatuta** [comment]
@Rahnar 

Я взял текущий актуальный [project-stub](https://github.com/bem/project-stub), добавил в него конфиг `.borschik` из комментария выше (https://github.com/bem/project-stub/blob/borschik-demo/.borschik) и создал блок `b1` с бекграундом с картиной (https://github.com/bem/project-stub/tree/borschik-demo/common.blocks/b1), результат запушил в ветку https://github.com/bem/project-stub/tree/borschik-demo

При сбоорке проекта картинка из `common.blocks/b1/` фризится в `img/`.

Если конфиги у тебя на проекте совпадают, то попробуй на всякий сбросить кэш сборки (`enb make clean`).

По поводу оставшихся вопросов:
>  1) когда я создам страницу новую в desktop.bundles например contact - скрипты подключать из папки index?

Лучше использовать merged-bundle (подробнее см. https://github.com/enb-bem/enb-bem-techs/blob/master/docs/build-merged-bundle.md).

> 2) я когда открыл файлик _index.js там очень много чего написанно было, я так понимаю это для использования i-bem.js, я пока его не использую , пишу на ваниле. Можно ли это как-то убрать , все что там написанно? Потому что там около 1000 или даже более строк лишнего кода. Хотя i-bem.js постараюсь разобрать в ближайшее время.

Насколько я понимаю, ты не используешь никаких БЭМ-библиотек, кроме `bem-core` ради BEMHTML? Если так, то проще всего просто скопировать из нее себе на проекте `i-bem.bemhtml`, `page.bemhtml` и `ua.bemhtml` (если нужен), а библиотеки просто исключить из сборки. Ну и как верно заметил @Guria, в сборку будет попадать `ym`. Чтобы от нее избавиться, можно собирать js, например, с помощью https://github.com/enb-make/enb/blob/master/techs/js.js вместо https://github.com/bem/project-stub/blob/bem-core/.enb/make.js#L85-L90

**Comment by Rahnar** [comment]
@tadatuta
У меня все получилось, спасибо! Единственное  не пойму , зачем он картинкам имена меняет? Я сохранил с именем 1.jpg , а на выходе, получил в папке img (lMmIQ3aOXdBf1S_MU5vsfSwbcHU.jpg) крокозяблу_)) Так должно быть?

**Comment by tadatuta** [comment]
@Rahnar да. «кракозябры» — это хешсумма от контента картинок. это нужно для того, чтобы сервер мог выставлять заголовки кэширования на максимально длительный срок, а разработчик не задумывался об инвалидации кэша.

**Comment by zxqfox** [comment]
Угу. :+1: вот такая штука

**Comment by Rahnar** [comment]
@tadatuta
Теперь понятно.Благодарю,  Владимир!Спасибо , за огромный труд и помощь. Спасибо всем,  кто помогал и не был равнодушным.

**Comment by Rahnar** [comment]
@tadatuta
Стал настраивать сейчас объединенные бандлы. Ошибку выдает.
Собственно, что делаю.
1) Создал я нужную папку (merged).
2) Скопировал туда из всех bundles  index.bemdecl.js и contact.bemdecl.js
3)Создал там файл merged.bemdecl.js закинул содержимое index и contact, по сути там все одинкого.
4) Скопировал в ./enb make.js тот скрипт который был дан.
5) Собственно все.  Что могу делать не правильно?

**Comment by tadatuta** [comment]
@Rahnar нужно было сделать только 4), все остальное скрипт делает автоматически

**Comment by Rahnar** [comment]
@tadatuta
Сейчас я положил  скрипт только в make.js (удалив старый). Теперь он создал папку , но все равно выдал ошибку.  Сервак запускает , а потом при обновлении страницы выдает это:
```javascript
TypeError: undefined is not a function
    at module.exports.inherit.addTech (/Users/R/Topfloat-mobile/node_modules/enb/lib/config/node-config.js:250:34)
    at /Users/R/Topfloat-mobile/node_modules/enb/lib/config/node-config.js:198:19
    at Array.forEach (native)
    at module.exports.inherit.addTechs (/Users/R/Topfloat-mobile/node_modules/enb/lib/config/node-config.js:197:15)
    at /Users/R/Topfloat-mobile/.enb/make.js:23:24
    at keepRunning (/Users/R/Topfloat-mobile/node_modules/enb/lib/config/configurable.js:50:44)
    at module.exports.inherit.exec (/Users/R/Topfloat-mobile/node_modules/enb/lib/config/configurable.js:54:16)
    at /Users/R/Topfloat-mobile/node_modules/enb/lib/make.js:325:48
    at Array.1 (/Users/R/Topfloat-mobile/node_modules/enb/node_modules/vow/lib/vow.js:202:56)
    at Object.callFns [as _onImmediate] (/Users/R/Topfloat-mobile/node_modules/enb/node_modules/vow/lib/vow.js:462:35)

```

**Comment by Rahnar** [comment]
Ребят, уже почти сутки сижу , никак не  разберу merged. То ли , тот туториал (https://github.com/enb-bem/enb-bem-techs/blob/master/docs/build-merged-bundle.md), уже не подходит к новой версии project-stub, либо я делаю что-то ни так. Уже и сам писал,  копипастил код который  был там... Кто-нибудь уже делал? К сожалению , мало инфы про это , мне не понятно..

**Comment by andrewblond** [comment]
@Rahnar привет!

Кажется, что в туториале тупо опечатка, и ошибка возникает именно поэтому. Вместо `tech.provideBemdecl` на 76 строке надо `techs.provideBemdecl`.

**Comment by Rahnar** [comment]
@andrewblond 
Приветствую! К сожалению, ошибка все равно осталась. Самое удивительное, что папку то он создает , а вот дальше прерывается..А у Вас , получалось делать такую настройку?

**Comment by zxqfox** [comment]
@Rahnar надо комментировать по очереди все технологии, начать с `/Users/R/Topfloat-mobile/.enb/make.js:23:24` — строки 23. Когда начнет выдавать другую ошибку — проверить что там добавляется и починить. Если другая ошибка после этого сохранится — разбираться с ней, или суда прислать.

**Comment by Rahnar** [comment]
И так , друзья! Я разобрался со своим недугом, время было потрачено не зря. Я до последнего верил, что код верно написан и косяки у меня. Собственно  - это касается всех тех, кто поставит ласт сборку project-stub  и когда вы захотите поставить "megred" Вам необходимо: 
```javascript
    вот это
    config.nodes('*.bundles/*', function (nodeConfig) {
        var node = path.basename(nodeConfig.getPath());
        if (node !== 'merged') {
            nodeConfig.addTechs([
                [techs.provide, { target: '?.bemdecl.js' }]
            ]);
        }
    });

   заменить на это( и будем вам счастье)

   config.nodes('*.bundles/*', function (nodeConfig) {
        var node = path.basename(nodeConfig.getPath());
        if (node !== 'merged') {
            nodeConfig.addTechs([
                [ require('enb/techs/file-provider') , { target: '?.bemdecl.js'}]
            ]);
        }
    });
```
Спасибо, надеюсь это кому-то поможет. У меня все работает как часики.

**Comment by Rahnar** [comment]
@zxqfox
```javascript 
   Заменил строчку 
       nodeConfig.addTechs([
            [ techs.provide , { target: '?.bemdecl.js'} ]
      ]);
     на
      nodeConfig.addTechs([
            [ provide , { target: '?.bemdecl.js'} ]
      ]);
```
Все собирает  и ошибок нет, но если вносить изменения например в index.bemjson.js , то он их не видит. При перезагрузки , он даже папки непересобирает.  А по адресу http://localhost:8080/  показывает схемы merged , но пишет (No pages are configured). Я так полагаю, так быть не должно.

**Comment by zxqfox** [comment]
@Rahnar Да, конечно не должно. Если я скажу, что для merged бандла нужно (для простоты) создать отдельную папку бандлов — я угадаю в чем дело?

**Comment by Rahnar** [comment]
@zxqfox
так она и так отдельная.  у меня идет 
index/
test/
merged/
куда собственно он складывает  *.bemdecl.js все моих бандлов. Вы об этом?

**Comment by andrewblond** [comment]
@Rahnar, да так быть не должно. В руководстве описан случай, когда мы собираем `merged` бандл, на основе `bemdecl.js` тагретов, а не на основе `bemjson.js`.

Чтобы заработало правильно надо тут:

```js
nodeConfig.addTechs([
    [ provide , { target: '?.bemdecl.js'} ]
]);
```

поменять на:

```js
nodeConfig.addTechs([
    [provide, { target: '?.bemjson.js' }],
    [techs.bemjsonToBemdecl],   
]);
```

**P.S.** Подумаю над тем как добавить этот кейс в руководство.

**Comment by Rahnar** [comment]
@andrewblond
Спасибо. Интересно, туториал ,  документацию в Яндексе пишут специально так, чтобы потом сидеть и додумывать  и допиливать самому. Типа, отгадай загадку и все заработает.

**Comment by Rahnar** [comment]
@andrewblond
 https://github.com/enb-bem/enb-bem-techs/blob/master/docs/build-merged-bundle.md обновите тут пожалуйста, рабочий вариант. Потому-что он там не верный.Конкретно с этим блоком, который выше.

**Comment by Rahnar** [comment]
@andrewblond
Я поменял,  тоже самое осталось.

**Comment by Rahnar** [comment]
@andrewblond
Поменял, к сожалению тоже самое. Сейчас буду дальше думать.

**Comment by zxqfox** [comment]
@Rahnar А поделись, пожалуйста, конфигом, если не сложно?
Хотя бы куском `config.nodes('*.bundles/merged', function (nodeConfig) {`

**Comment by Rahnar** [comment]
@zxqfox
Тут кинул часть папок. Там make и  внутри папки touch-phone.bandles все остальное
https://github.com/Rahnar/Topfloat-mobile

**Comment by Rahnar** [comment]
@zxqfox Удалось посмотреть?

**Comment by zxqfox** [comment]
https://github.com/Rahnar/Topfloat-mobile/blob/master/.enb/make.js#L33 — я могу ошибаться, но этот кусок про bemdecl не будет работать с bemjson, как @andrewblond выше констатировал.

Нужно дополнительно собрать bemdecl из bemjson (techs.bemjsonToBemdecl), затем [mergeBemdecl](https://github.com/Rahnar/Topfloat-mobile/blob/master/.enb/make.js#L47), и затем сборка.

**Comment by zxqfox** [comment]
@andrewblond `https://github.com/Rahnar/Topfloat-mobile/blob/master/.enb/make.js#L21` — фуфу, кстати.

**Comment by zxqfox** [comment]
@Rahnar https://github.com/Rahnar/Topfloat-mobile/blob/master/.enb/make.js#L37 — вот это точно неправильно. Но как правильно не уверен, потому что если нужно `[provide, { target: '?.bemjson.js' }],` — то я не понимаю, как там что работает внутри и не смогу ответить точно ;-)

**Comment by Rahnar** [comment]
@zxqfox
Я сам уже ниче не понимаю!) А Вы сами такую штуку настраивали?У Вас получалось??

**Comment by zxqfox** [comment]
Судя по доке:
https://github.com/enb-bem/enb-bem-techs#providebemdecl
https://github.com/enb-bem/enb-bem-techs#bemjsontobemdecl

https://github.com/Rahnar/Topfloat-mobile/blob/master/.enb/make.js#L36-L44
```js
var node = path.join(dir, bundle),
    bemjsonTarget = bundle + '.bemjson.js';
    target = bundle + '.bemdecl.js';

nodeConfig.addTechs([
    [techs.bemjsonToBemdecl, {
        source: bemjsonTarget,
        target: target
    }],
    [techs.provideBemdecl, {
        node: node,
        target: target
    }]
]);
```

Может так? ошибка будет какая-то?

**Comment by Rahnar** [comment]
```javascript
Последствия
Error: Concurrent techs for target: form.bemdecl.js, techs: "bemjson-to-bemdecl" vs "provide-bemdecl"
    at Error (<anonymous>)
    at module.exports.inherit._registerTarget (/Volumes/Macintosh HD 2/Work/TopFloat/Topfloat-mobile/node_modules/enb/lib/node.js:451:19)
    at registerTarget (/Volumes/Macintosh HD 2/Work/TopFloat/Topfloat-mobile/node_modules/enb/lib/node.js:579:31)
    at Array.forEach (native)
    at /Volumes/Macintosh HD 2/Work/TopFloat/Topfloat-mobile/node_modules/enb/lib/node.js:582:40
    at Array.3 (/Volumes/Macintosh HD 2/Work/TopFloat/Topfloat-mobile/node_modules/enb/node_modules/vow/lib/vow.js:202:56)
    at Object.callFns [as _onImmediate] (/Volumes/Macintosh HD 2/Work/TopFloat/Topfloat-mobile/node_modules/enb/node_modules/vow/lib/vow.js:462:35)
    at processImmediate [as _immediateCallback] (timers.js:354:15)


```

**Comment by zxqfox** [comment]
@Rahnar получается, что если есть techs.provideBemdecl — то нужны файлы bemdecl собранные, а если их собирать из bemjson — то они параллельно провайдятся и конфликтуют...

Может если provideBemdecl норм будет? Других идей нет ;) Только лезть в технологии и разбираться, что там происходит. Мб писать provideBemdeclFromBemjson...

**Comment by andrewblond** [comment]
@Rahnar, если добавишь директорий `touch-phone.blocks` и `touch-pad.blocks` то у тебя всё хорошо работает же ;)

**Comment by Rahnar** [comment]
@zxqfox
Тоже самое.  Жизнь боль.До конца недели буду решать что-то. Не хотелось бы от БЭМ отказываться, только полюбил его.Но если так дальше будет плохо...

**Comment by zxqfox** [comment]
@andrewblond А гарантии есть, что bemdecl.js будут собраны до merged?

**Comment by andrewblond** [comment]
> А гарантии есть, что bemdecl.js будут собраны до merged?

Да, конечно.

**Comment by Rahnar** [comment]
@andrewblond
В make.js добавить?Или куда конкретно?Уже голова не варит под конец раб дня.

**Comment by andrewblond** [comment]
@Rahnar, на файловую систему. Рабочий вариант, это — https://github.com/Rahnar/Topfloat-mobile/blob/master/.enb/make.js.

**Comment by Rahnar** [comment]
@andrewblond
  Все так отказывается собирать и видеть другие страницы.. 
Как избавиться от такой хрени?
Error: EEXIST, mkdir '/Users/R/test-mobi/touch-phone.bundles/.DS_Store'  .DS_Store  - из-за файлика служебного ошибка летит в добавок.

**Comment by andrewblond** [comment]
@Rahnar, странно, что ни у кого раньше проблема производилась...

Попробуй вместо:

```js
if (bundle === 'merged') return;
```

Написать следующее:

```js
if (bundle === 'merged' || bundle.charAt(0) === '.') return;
```

**Comment by Rahnar** [comment]
@andrewblond
Тоже самое.
Я создал сейчас новый проект.  Состоит он,  только из одной desktop.bundles.  Тач не брал. Скопировал свой код в make.js. Поменял в массиве в самом верху на desktop, а внизу указал desktop.blocks. make запустил, все создал и собрал он. Открываю сервак , весят схемы  merged и написанно (No pages are configured).

**Comment by andrewblond** [comment]
@Rahnar, я правильно понял, что нету html файла в merged-бандле? Если так, то это ожидаемое поведение. Задача merged-бандла — собрать нужные файлы технологий (css, js), которые включают в себя блоки со всех страниц. 

Нужно настроить сборку HTML на основе BEMJSON для всех страниц, кроме merged-бандла. А в страницах использовать `css` и `js` merged-бандла. 

Как настроить сборку страницы можно почитать тут — https://github.com/enb-bem/enb-bem-techs/blob/master/docs/build-page.md. Но из такого конфига нужно будет выпилить сборку `css` и `js`, т.к. они уже собираются в merged-бандле.

**Comment by Rahnar** [comment]
@andrewblond
Задача изначально стояла такая, вот есть у меня бандлы(страницы) разные.  И надо чтобы все страницы имели один файл со стилями и скриптами. Тобишь в финальной сборке у меня в файлике например merged.css все стили страниц , а в файлике merged, все скрипты от всех страниц. Просто я как себе представлял, что я спокойно работаю как обычно, и все автоматом сливается в единый файлик со стилями и скриптами.

**Comment by tadatuta** [comment]
@Rahnar все так и есть. остается лишь в `index` подключить `_merged.css` и `_merged.js` вместо `_index.css` / `_index.js` (и аналогично для остальных страниц).

**Comment by Rahnar** [comment]
@tadatuta
Я это понял, Владимир. Моя сейчас проблема состоит в том, что он не хочет собирать и видеть другие бандлы. Я вношу изменения в index.bemjson.js сохраняю , перезагружаю и ничего не происходит. Страниц самих нет. Вот, я сейчас сижу , настраиваю, чтобы он собирал мне эти страницы. Все остальное , в папку merged прилетает как надо. И он кстати ругается на системные файлы .DC_Store это на маке, при сборке)) Сталкивались с таким?Видать из-за того , что он создает папку merged и он автоматом создает служебный файлик этот.

**Comment by tadatuta** [comment]
@Rahnar нет, никогда не сталкивался. если есть возможность выложить на github проект, помогу разобраться

**Comment by Rahnar** [comment]
@tadatuta
Сегодня выложу Вам. Но, пришлю лично на почту. Хорошо?

**Comment by tadatuta** [comment]
конечно

**Comment by Rahnar** [comment]
Хочу показать свой готовый и рабочий вариант сборки merged  бандла, возможно он не так красив, но выполняет то , что я хотел в итоге получить. Буду дорабатывать его и улучшать , по мере накопления знаний по node.js )) ( https://github.com/Rahnar/Topfloat-mobile/blob/master/.enb/make.js ). Пример для touch устройства.Его можно вставлять и сразу использовать. Конечно , если Вам нужно для других устройств , код придется  дооформить самому, под нужды.  Благодаря Владимиру (tadatuta) , исправлена проблема с ошибкой DC_Store , она может появиться у пользователей macOS, как это было у меня. Огромное спасибо, за предоставленный вариант решения!
Единственное, хотелось бы узнать , как избежать конфликты кода в едином js? Пока идея приходит только такая: "Куски кода, оборачивать в if и прописывать location, чтобы он срабатывал только на нужной нам url, например для контактов будет:
```javascript
 var url = window.location.pathname;
  if( url === '/contact.html'   ||  url === '/' ){
    Какой-то код.
 }
```

**Comment by tadatuta** [comment]
> как избежать конфликты кода в едином js

Вариантов достаточно много, все зависит от задачи.
Например, можно давать конфликтующим блокам непересекающиеся модификаторы или вообще называть блоки по-разному (если они выглядят одинаково и только имеют разный JS, то можно миксовать общий блок про внешний вид с разными блоками про JS на одном DOM-узле).

Еще для тачевой версии можно подумать в сторону одностраничного приложения, ведь каждая перезагрузка страницы — это лишние накладные расходы, которых на медленном 3g хочется избежать.

**Comment by Rahnar** [comment]
@tadatuta
Там встала проблема такая, что у меня на одной странице идет инициализация плагина, а на другой странице, нет. В итоге он его пытается инициализировать(плагин) на странице , где это совсем не требуется.При этом требует  подключения библиотеки jquery соотвественно. Как-то так.

**Comment by tadatuta** [comment]
@Rahnar вроде это ничему не противоречит

**Comment by Rahnar** [comment]
@tadatuta Да , да. Это мысли в слух были. Я уже сделал )))

**Comment by Rahnar** [comment]
Доброй ночи  , ребят. А где можно посмотреть скрипт , который создает в наших бандлах файлы c html , css , js. Там же прописано куда их именно при компиляции складывать их.

**Comment by Guria** [comment]
Курить в направлении документации enb-make

**Comment by Rahnar** [comment]
@Guria
Уже)Но, то  что я хотел сделать, плохая была идея.

**Comment by Rahnar** [comment]
@Guria
Где можно посмотреть нормальное  описание того, как пользоваться file-copy штукой.

**Comment by andrewblond** [comment]
@Rahnar, https://github.com/enb-make/enb/blob/master/techs/file-copy.js#L1-L22 этого описания не хватает?

**Comment by Rahnar** [comment]
@andrewblond
Не очень, если честно. Сижу разбираю. Я ток постигаю весь Дзен и пока что еще глуп и невежествен. ) Кстати, эта штука решает проблему с путями? Фризить картинки я научился, но , вот когда я уже вытаскиваю файлы из бандлов и кладу все в одну папочку, В html пути аля ../../ и в сss у картинок, тоже самое. Пока что в ручную перебиваю на нужные. Со сборкой прям боль какая - то. Все остальное все замечательно.

**Comment by andrewblond** [comment]
> Кстати, эта штука решает проблему с путями?

Нет, она по задумке глупая и не знает ничего содержимое.

> Фризить картинки я научился, но , вот когда я уже вытаскиваю файлы

А можешь набросать схему: что после сборки, и куда потом надо перенести? Может быть можно сразу собирать так, чтобы потом не переносить.

**Comment by Rahnar** [comment]
@andrewblond
```blockquote
    /build
      /img
          i.jpg
      merged.css
      merged.js
      index.html      
```
Вот такая схема:  
Я из всех bundle, собираю ?.html и кладу в папку build. В bemjson  картинки  которые вставляются тегом,  у них пути до папки img прописаны сразу. я их туда складываю. Тобишь (../../img/1.jpg) выходим из  bundle , потом из desktop.bundles ,заходим в папку img и наша картинка. Я так понимаю, он фризить не умеет картинки которые мы вставляем непосредственно как тэг, из css все норм летит. Все что в  сss, он их все бросает в папку img. Но в конечном итоге, у merged.css пути до файлов ../../img/2.jpg так как, он проходит такую же процедуру путей как я описал выше, только автоматом. В итоге , вынимая все из бандлов и складывая по схеме выше, у нас пути остаются ../../  вот такие. Да и это касается еще подключение стилей и скриптов , нам же надо например в index.bemjson прописать такого типа путь (../merged/_merged.css)  до единого css  и js. 
Потом что структура вот такая: 
  ```blockquote

  index/
        index.bemjson
  merged/
        _merged.css
```
А  на выходе , в папке build у html по прежнему пути ../merged/merged.css  и приходиться убирать (../merged/). Так же и у css убирать лишнее.

**Comment by ron116** [comment]
@Rahnar, у вас получилось настроить нормальную сборку слияния js, css файлов ? 
Я тоже столкнулся с этой проблемой. Этот https://github.com/enb-bem/enb-bem-techs/blob/master/docs/build-merged-bundle.md рецепт не работает.

**Comment by Rahnar** [comment]
@ron116
Получилось, но он грешит потихоньку. Вы можете воспользоваться примером , но там надо поколдовать . Я чуть позже скину обновленный вариант.

**Comment by ron116** [comment]
@Rahnar, какой пример вы имеете в виду ?

**Comment by Rahnar** [comment]
@ron116
 https://github.com/Rahnar/Topfloat-mobile/blob/master/.enb/make.js

**Comment by tadatuta** [comment]
@Rahnar возможно будет интересно: https://github.com/bem/project-stub/compare/merged?expand=1

**Comment by Rahnar** [comment]
@tadatuta
Весьма интересно!!) Спасибо!)

**Comment by Rahnar** [comment]
.

**Comment by vithar** [comment]
@tadatuta, @blond, то, что делает @rahnar весьма частый для статической вёрстки и потом передачи её программистам случай, давайте это или упростим максимально (написав отдельную технологию?) или опишем отдельно и подробно.

**Comment by zxqfox** [comment]
А не хотите gulp поверх enb?

**Comment by tadatuta** [comment]
@vithar «у нас про это есть задача»: https://github.com/enb-bem/enb-bem-techs/issues/119

**Comment by tadatuta** [comment]
@zxqfox ты же знаешь, хотим gulp без enb ;)

**Comment by Rahnar** [comment]
@tadatuta @vithar @zxqfox
Короче,  сегодня такая ситуация была на работе, у нас на проекте основной фреймверк это ангулар. И пришлось использовать альфабанковский проект, чтобы чувак смог писать свои  ng-штуки  непосредственно в самом bemjson . Потому что без этой bem-ng надстройки , на обычном enb - project-stub работать не будет, расстроился из-за того что  i-bem и ангулар мешают друг другу, и потом невозможно использования bem-component. Ну так вот, там же gulp используется , и хочу сказать, весьма удобно. Правда bem-tools работает весьма медленно , с тем же  enb. Хотя я ангуларом не пользуюсь , пишу ток на нативе или вот i-bem стал юзать.

**Comment by zxqfox** [comment]
@Rahnar Ну нейтив (или vanilla) оно само собой разумеется, но с BEM-деревом работать гораздо удобнее, если подтянуть 10 килобайт i-bem поверх jquery. А ангуляр — сомнительная затея, имхо ;-)

**Comment by Rahnar** [comment]
Если бем будет под gulp  разлетится и станет мейнстримом )))Да еще модули люди начнут под него писать)

**Comment by Rahnar** [comment]
@zxqfox
А разве i-bem решает те же задачи что и ангулар? 
@tadatuta
За merged спасибо , очень круто все работает!

**Comment by zxqfox** [comment]
@Rahnar не, `i-bem` решает задачу работы с BEM-деревьями и BEM-нодами. А что у вас в BEM-дереве — вы уж сами смотрите. Единственная несостыковка у `angular` и `i-bem`, это то, что они оба работают с DOM. И когда один из них что-то меняет в DOM, второй продолжает работать со своим кешом и теряется. Если же научить angular работать с BEM-деревьями, то половину ангуляра, скорее всего, можно будет выкинуть, а остальное будет компактнее, понятнее, и проще. Имхо ;-)

**Comment by Guria** [comment]
Постепенно начинаю скрещивать в нашем проекте ангуляр с i-bem. Не вижу принципиальной проблемы:
Создал директиву которая в link из небольшого bemjson с помощью bemtree+bemhtml генерирует html причём возможно с data-binding вставками.
На полученный dom натравливается bemdom.init и ангуляровский $compile. Все. Этот кусок dom предоставлен компонентам на i-bem. Ангуляру доверели только data-binding на текстовых нодах.

**Comment by zxqfox** [comment]
> Ангуляру доверели только data-binding на текстовых нодах.

Вот то-то и оно!

**Comment by Guria** [comment]
Ну приложение в целом на ангуляре осталось. А это только маленький компонент, в котором ангуляру внутри делать особенно нечего.

**Comment by Rahnar** [comment]
@Guria
А как решаешь вопрос с ng-model ?
