### ISSUE TITLE
Добавление БЭМ-сущностей для задач вёрстки не работает

### ISSUE THREAD

**Issue by raulleo** [bem/bem-forum-content-ru#343]
Пример [Добавление БЭМ-сущностей для задач вёрстки](https://ru.bem.info/technology/bemhtml/v2/reference/#Добавление-БЭМ-сущностей-для-задач-вёрстки) из руководства по BEMHTML выдает ошибку:
```
Error: Only literal or function is allowed in template's body
   at Compiler.assert (/vagrant/project-stub/node_modules/enb-bemxjst/node_modules/bem-xjst/node_modules/xjst/lib/xjst/compiler/base.js:180:9)
   at Compiler.transformTemplates (/vagrant/project-stub/node_modules/enb-bemxjst/node_modules/bem-xjst/node_modules/xjst/lib/xjst/compiler/base.js:648:8)
   at Array.map (native)
   at Compiler.translate (/vagrant/project-stub/node_modules/enb-bemxjst/node_modules/bem-xjst/node_modules/xjst/lib/xjst/compiler/base.js:201:41)
   at Object.translate (/vagrant/project-stub/node_modules/enb-bemxjst/node_modules/bem-xjst/node_modules/xjst/lib/xjst/api.js:16:40)
   at Compiler.translate (/vagrant/project-stub/node_modules/enb-bemxjst/node_modules/bem-xjst/lib/bemhtml/compiler.js:121:35)
   at Compiler.generate (/vagrant/project-stub/node_modules/enb-bemxjst/node_modules/bem-xjst/lib/bemhtml/compiler.js:707:14)
   at Object.generate (/vagrant/project-stub/node_modules/enb-bemxjst/node_modules/bem-xjst/lib/bemhtml/api.js:16:40)
   at require.declare.process (/vagrant/project-stub/node_modules/enb-bemxjst/techs/bem-xjst.js:7:28)
   at /vagrant/project-stub/node_modules/enb-bemxjst/node_modules/sibling/lib/runner.js:22:48
```

Гугление подсказало обернуть матчинг флага в анонимную функцию:
```
block('box').match(function() { return !this.ctx._processed; })
```

Не помогло.

Обернул вызов applyCtx:
```
block('box').match(function() { return !this.ctx._processed; }).content()(function() {
    applyCtx({'ctx._processed':true}, {
        elem: 'left-top',
        content: {
            elem: 'right-top',
            content: {
                elem: 'right-bottom',
                content: {
                    elem: 'left-bottom',
                    content: applyNext()
                }
            }
        }
    });
})
```

Ошибка пропала, но html сгенерировался криво:
```
<div class="box">
    <div class="box">text</div>
    <div class="box__left-top">
        <div class="box__right-top">
            <div class="box__right-bottom">
                <div class="box__left-bottom"></div>
            </div>
        </div>
    </div>
</div>
```

Подскажите, как правильно делать такую банальную вещь?

**Comment by tavriaforever** [comment]
1. Об apply.. хорошо написано тут https://ru.bem.info/forum/issues/174/
2. В твоем случае тебе нужно положить пачку оберток внутри блока и в этом случае меня контекст и вызывать `applyCtx` не нужно , а поэтому достаточно будет:

```
block('box')(
    content()(function() {
        return {
            elem: 'left-top',
            content: {
                elem: 'right-top',
                content: {
                    elem: 'right-bottom',
                    content: {
                        elem: 'left-bottom',
                        content: applyNext()
                    }
                }
            }
        };
    })
);
```

**Comment by raulleo** [comment]
@tavriaforever от applyCtx я, в первую очередь, ожидал, что стили вложенных блоков подключатся автоматически.

Если переписывать контент куском bemjson, приходится создавать файл box.deps.js:
```
({
    shouldDeps: [
        { elem: 'left-top' },
        { elem: 'right-top' },
        { elem: 'right-bottom' },
        { elem: 'left-bottom' }
    ]
})
```
Не хотелось бы писать зависимости для каждого враппера.

**Comment by Guria** [comment]
Нет смысла такие стили раскидывать по папкам. Пишите их в рамках стилей 'box'

**Comment by sipayRT** [comment]
Согласен с @Guria Но на будущее - твою запись депсов можно сократить до 

```
({
    shouldDeps: [
        { elems: ['left-top', 'right-top', 'right-bottom', 'left-bottom']
    ]
})
```

**Comment by raulleo** [comment]
@Guria @sipayRT а если примиксован другой блок со своими технологиями к одному из вложенных элементов?
```
block('box')(
    content()(function() {
        return {
            elem: 'left-top',
            mix: { block: 'box2' }
            content: applyNext()
        };
    })
);
```

**Comment by veged** [comment]
@raulleo зависимости нужно писать в любом случае — доставать зависимости из bemhtml программы это не тривиальная задача, т.к. может быть написано `var res = {}; if(...) res.elem = myVar;` и т.п. (см. также https://github.com/bem/bem-forum-content-ru/issues/298#issuecomment-83813859)

**Comment by varya** [comment]
@veged А давайте писать зависимости как в Ангуляре? Ну, всмысле не прямо так, а по такой же идее. Вначале css-файла делать `@import` нужных. В начале js-файлов уже всё написано, там же модульная система. И для bemhtml что-нибудь подобное ввести. Потом сборщик всё это считывает и собирает так же как сейчас.

**Comment by apsavin** [comment]
@varya таким образом, кажется, можно выразить только mustDeps из текущего формата описания зависимостей. Как быть с depsByTech и shouldDeps?

**Comment by apsavin** [comment]
@varya кстати, `@import` в css файле и блок в зависимостях - это разные вещи. `@import` вставляет столько раз, сколько его напишешь, а блок в сборку попадет только один раз.

**Comment by varya** [comment]
mustDeps и shouldDeps различать тем, в начале файла написана зависимость или в конце.
Ну для depsByTech так и быть можно как сейчас сделать. Главное что если в файле писать для простых случаев, то похоже на другие системы и сразу ниже порог вхождения.

**Comment by apsavin** [comment]
@varya Я, кстати, слышал про технологию для enb, которая зависимости собирает по тому, что в js-файлах указано, но сейчас ее найти не могу.

**Comment by tadatuta** [comment]
@apsavin https://github.com/enb-make/enb-modules/blob/master/techs/deps-with-modules.js

**Comment by zxqfox** [comment]
@varya @apsavin Идея крутая, но это будет каша...

**Comment by blond** [comment]
`@import` в css-файлах это и есть чесный `depsByTech`, но только для `css` технологии. 

Это значит, что для построения CSS-файлов не обязательны DEPS-файлы, и может быть достаточно только кода. Чтобы построить шаблоны и прочее, по-прежнему смотрим в DEPS-файлы и не смотрим в CSS.

Но и совсем без обычных DEPS-ов не обойтись.

**Пример:**

Допустим, что нам нужна кнопка. в BEMJSON-файле она будет записана так:

```js
{
    block: 'button',
    text: 'Buy!'
}
```

Из BEMJSON получаем декларацию:

```js
[
    { block: 'button' }
]
```

Исходный код шаблонов:

`button.bemhtml`

```js
block('button').content(function () {
    return {
        elem: 'text',
        content: this.ctx.text;
    };
});
```

Для шаблонов пишем зависимости:

`button.deps.js`

```js
{
    shouldDeps: { elem: 'text' }
}
```

Дополняем декларацию зависимостями:

```js
[
    { block: 'button' },
    { block: 'button' elem: 'text' }
]
```

Исходные файлы CSS-файлы:

`button.css`

```css
.button {
    padding: 10px 15px;
    border: 1px solid #000;    
}
```

`button__text.css`

```css
.button__text {
    color: #000;
}
```

По дополненной декларации, строим CSS-файл:

```css
.button {
    padding: 10px 15px;
    border: 1px solid #000;    
}

.button__text {
    color: #000;
}
```

Если бы мы для шаблонов написали зависимости вида `depsByTech`

```js
{
    tech: 'bemhtml',
    shouldDeps: { elem: 'text' }
}
```

То в результирующий CSS-файл, не попал бы код элемента `button__text`, и это было бы ошибкой. При этом `button.css` никак не зависит от `button__text` и использовать `@import` тут было бы не уместно.

`@import` больше подойдёт для случая с модификатором, например:

`button_size_m.css`

```css
@import "button__text";

.button_size_m .button__text {
    font-size: 16px;
    line-height: 20px;
}
```

Т.е. я бы рассматривал `@import` как что-то дополняющее DEPS-файлы, но не заменяющее их.

**Comment by blond** [comment]
@zxqfox почему будет каша?

@varya вариант с `@import` в конце файла, кажется, не очень очивидным. Тем более, это не чесный аналог `shouldDeps`: код из `@import` будет всегда снизу.

> кстати, @import в css файле и блок в зависимостях - это разные вещи. @import вставляет столько раз, сколько его напишешь, а блок в сборку попадет только один раз.

@apsavin это же не мешает настроить сборщик таким образом, чтобы код вставлялся только один раз.

> Как быть с depsByTech и shouldDeps?

@apsavin Если рассматривать `@import` как нечто дополняющее, то можно всегда считать, что это `mustDeps` а для остальных случаев есть DEPS-файлы.

**Comment by apsavin** [comment]
@blond 
> Как быть с depsByTech и shouldDeps?
@apsavin Если рассматривать @import как нечто дополняющее, то можно всегда считать, что это mustDeps а для остальных случаев есть DEPS-файлы.

Собственно, я вот к этому и писал:

> Но и совсем без обычных DEPS-ов не обойтись.
