### ISSUE TITLE
bem-tool поиск ошибки

### ISSUE THREAD

**Issue by kompolom** [bem/bem-forum-content-ru#392]
В какой то момент перестала работать сборка. вываливается с таким кодом. Подскажите, как узнать, где конкретно ошибка?

````
TypeError: Cannot read property 'name' of null
    at /home/jenik/projects/haywedding/haywedding/bem/node_modules/bem/lib/techs/v2/deps.js.js:241:25
    at Array.forEach (native)
    at forEachItem (/home/jenik/projects/haywedding/haywedding/bem/node_modules/bem/lib/techs/v2/deps.js.js:235:94)
    at /home/jenik/projects/haywedding/haywedding/bem/node_modules/bem/lib/techs/v2/deps.js.js:289:21
    at Array.forEach (native)
    at forEachItem (/home/jenik/projects/haywedding/haywedding/bem/node_modules/bem/lib/techs/v2/deps.js.js:235:94)
    at /home/jenik/projects/haywedding/haywedding/bem/node_modules/bem/lib/techs/v2/deps.js.js:287:21
    at Array.forEach (native)
    at forEachItem (/home/jenik/projects/haywedding/haywedding/bem/node_modules/bem/lib/techs/v2/deps.js.js:235:94)
    at Object.exports.Deps.INHERIT.parse (/home/jenik/projects/haywedding/haywedding/bem/node_modules/bem/lib/techs/v2/deps.js.js:294:9)
````

**Comment by tadatuta** [comment]
@kompolom судя по всему ошибка где-то в районе депсов.

Чтобы получить какие-то подсказки, можно добавить `console.log('item', item)` в `node_modules/bem/lib/techs/v2/deps.js.js` перед 241 строкой, перезапустить сборку, найти в консоли, на чем именно падает и поискать вхождения в deps-файлах проекта. Ну или просто посмотреть по последним коммитам, что менялось в *.deps.js.

**Comment by kompolom** [comment]
В данном  случае `item` это блок с зависимостью, или сама зависимость?
Приведу конец вывода `bem make`:

````
item { name: 'button' }
item { name: 'rvars', mods: [ { name: 'lang', vals: [Object] } ] }
item { name: 'lang', vals: [ null ] }
item null
01:13:44.581 - info: [t] Build time for "desktop.bundles/index/index.deps.js" [1]: 650ms
01:13:44.582 - info: [t] Build total: 1404ms
TypeError: Cannot read property 'name' of null
````

**Comment by kompolom** [comment]
@tadatuta Спасибо! Проблема оказалась в  `bemjson` где одному из модификаторов присваивалось значение `null`
