### ISSUE TITLE
тестирование блоков

### ISSUE THREAD

**Issue by kompolom** [bem/bem-forum-content-ru#422]
Подскажите что почитать/посмотреть чтобы начать писать тесты на блоки. В первую очередь интересует browser.js

**Comment by blond** [comment]
Можешь посмотреть на пакет [enb-bem-specs](https://github.com/enb-bem/enb-bem-specs) для сборки и запуска тестов на клиенский js.

Примеры, можно смотреть в bem-components, в файлах [block.spec.js](https://github.com/bem/bem-components/blob/v2/common.blocks/button/button.spec.js).

**Comment by kompolom** [comment]
Спасибо за ответ. Попробовал, добавил конфиг, теперь проект не собирается.

````
Error: Cannot find module 'enb-bem-examples'
    at Function.Module._resolveFilename (module.js:338:15)
````

Я сначала подумал, что я конфиг неправильно написал. Потом проверил на `bem-grid` - enb make то же самое выдает....

**Comment by kompolom** [comment]
Можно как то добавить проекту тесты не ломая сборку по `enb make` ?

**Comment by blond** [comment]
Можешь показать конфиг? 

Для сборки тестов подключать модуль `enb-bem-examples` не нужно. Ошибка из-за того, что в конфиге есть подключение этого модуля, но в node_modules этого пакета нет.

**Comment by kompolom** [comment]
Конфиг. https://github.com/bem/bem-components/blob/v2/.enb/make.js
Клонирую bem-components
npm install
enb make

````
jenik@M50SA:~/projects/bem-components$ enb make
Error: Cannot find module 'enb-bem-examples'
    at Function.Module._resolveFilename (module.js:338:15)
````

**Comment by blond** [comment]
Сделал всё тоже самое, всё работает :)

Может кэш в npm сломался? `npm cache clean`

**Comment by kompolom** [comment]
не помогло...

**Comment by kompolom** [comment]
Пробовал на разных репозиториях с разных машин. Не собирается. ни bem-core, ни bem-components, ни другие пакеты с enb-bem-specs

**Comment by blond** [comment]
Можешь написать версию `Node.js` и `npm`?

```
node -v
npm -v
```

ENB используешь локально?

С такой же ошибкой падает?

После `npm i` какие модули есть в `node_modules`?

```
ls node_modules
```

**Comment by kompolom** [comment]
````
{"node":"v0.10.29","npm":"1.4.14"}{"node":"v0.10.29","npm":"1.4.14"}
````
````
11:34 jenik@baranov-pc:~/bem-components$ ls node_modules/
bem                     borschik-tech-cleancss  enb-bem-docs        enb-bh              enb-stylus   jscs-bem
bem-environ             bower                   enb-bem-examples    enb-borschik        gemini       jshint
bem-naming              bower-npm-install       enb-bem-specs       enb-diverse-js      git-hooks    jshint-groups
bem-tools-autoprefixer  csscomb                 enb-bem-techs       enb-magic-factory   http-server  stylus
bh                      enb                     enb-bem-tmpl-specs  enb-magic-platform  istanbul     svgo
borschik                enb-bembundle           enb-bemxjst         enb-modules         jscs         ym
````
enb установлен глобально. 
локальный собирает успешно

**Comment by blond** [comment]
> enb установлен глобально. 

Не надо так делать :) Лучше настрой переменную окружения `$PATH`.

**Comment by kompolom** [comment]
> Не надо так делать :) 

Теперь я даже знаю почему ))

**Comment by apsavin** [comment]
А никто не собирается написать enb-cli по аналогии с bem-cli?

**Comment by tadatuta** [comment]
@apsavin а в нем правда есть смысл? ставить глобальный пакет, который умеет делать то, что делает
```bash
export PATH=./node_modules/.bin:$PATH
```
только для одного конкретного пакета, вместо универсального решения?

**Comment by blond** [comment]
@tadatuta надо просто везде в документации писать про `$PATH`

**Comment by apsavin** [comment]
@tadatuta ну он слегка поумнее)
Может и нет смысла, особенно если enb звать через какой-то таск раннер.

**Comment by zxqfox** [comment]
@tadatuta А еще export не работает нигде, кроме sh/zsh/bash/tsh (кажется, никого не забыл), и, естественно, под виндой тоже не работает без доп магии ;-)

**Comment by tadatuta** [comment]
@zxqfox без вменяемой оболочки с большой долей вероятности и сам ENB работать не будет
А в bem-tools я даже веточку запилил с поддержкой ENB: https://github.com/bem/bem-tools/compare/support/0.10.x
Осталось всего ничего: убедиться, что ничего ничего не ломаю, начать сыпать варнинги при использовании bem make, обновить доки и можно выпускать.

**Comment by zxqfox** [comment]
@tadatuta :+1:

p.s. вспоминается баян про php7, который после php5, потому что php6 не вышло ;-(

**Comment by trebushuk** [comment]
Подобная ошибка с enb-bem-docs
enb установлен локально

```
% node_modules/.bin/enb make
Error: Module "enb-bem-docs" is not registered.
```
```
node -v
v6.9.5

npm -v   
1.4.9
```

```
autoprefixer      bower             enb-bem-techs      enb-postcss   postcss-import       rebem-css
bem               enb               enb-bemxjst        merge2        postcss-nested       through2-filter
bem-components    enb-beautify      enb-borschik       postcss-calc  postcss-reporter     ym
bem-core          enb-bem-docs      enb-js             postcss-each  postcss-simple-vars
bem-tools-create  enb-bem-examples  enb-magic-factory  postcss-for   postcss-url
```

**Comment by Yeti-or** [comment]
А если c npm -v 3.x
переустановив модули ( rm -rf node_modules && npm i)
тоже самое?

**Comment by tadatuta** [comment]
Есть подозрение, что проблема где-то в конфиге `.enb/make.js`

// cc @blond

**Comment by trebushuk** [comment]
@Yeti-or Несколько раз безуспешно обновлял npm пока не догодался проверить `where npm`
Оказалось было две версии и вызывалась всегда меньшая
```
-> /usr/local/bin/npm v.1.4.9
-> /usr/bin/npm v.4.2.0
```
Переустановил пакеты с новой версией `rm -rf node_modules && npm i`
И ничего ошибка таже `Error: Module "enb-bem-docs" is not registered.`
@tadatuta Конфиг взят из `project-stub` за исключением строк:
```
    // Docs
    config.includeConfig('enb-bem-examples'); // Подключаем модуль `enb-bem-examples`.

    var examples = config.module('enb-bem-examples') // Создаём конфигуратор сетов
        .createConfigurator('examples');             //  в рамках `examples`-таска.

    examples.configure({
        destPath: 'set.examples',
        levels: ['blocks'],
        inlineBemjson: true
    });


    var docs = config.module('enb-bem-docs').createConfigurator('docs', 'examples');
    docs.configure({
        destPath: 'set.docs',
        levels: levels,
        exampleSets: ['set.examples']
    });
```
Examples взят из примера в документации, Docs из `enb-bem-docs/examples/examples/.enb/make.js`
А вот весь [commit](https://github.com/trebushuk/project-stub/commit/1149b2a1dfe13d0d24a1c8fd1ef0fbf40ee3f147) из форка project-stub с этими правками.

**Comment by tadatuta** [comment]
@trebushuk все хорошо, просто потерялась строка `config.includeConfig('enb-bem-docs');`

Важный момент, который стоит учитывать: в качестве уровней указан `blocks`. Если это действительно то, что ожидается, то необходимо эту папку заранее создать. Либо указать реальные уровни проекта.

Ну и запускать сборки нужно так: `magic make set.docs`.
Еще может быть удобно запустить `magic server` и смотреть результаты в браузере по `http://localhost:8080/set.docs`.
