### ISSUE TITLE
Почему возникает ошибка на  yo bem-stub

### ISSUE THREAD

**Issue by mathetes** [bem/bem-forum-content-ru#462]
При запуске второго шага:  yo bem-stub

по видео мастер классу генерации проекта workshop получаю такой результат

 node bfs-workshop.js verify
Проверяем правильность задания. Пожалуйста, подождите.
✗ Вы должны установить generator-bem-stub с необходимыми параметрами.

# FAIL

Ваше решение к Генерация заготовки проекта не верное. Пробуйте еще!

✗ Вы должны установить generator-bem-stub с необходимыми параметрами.
/home/roman/frontend/workshop/do-it-yourself-workshop/node_modules/workshopper-exercise/exercise.js:152
    processors[i].call(self, mode, function (err, pass) {
                 ^
TypeError: Cannot read property 'call' of undefined
    at next (/home/roman/frontend/workshop/do-it-yourself-workshop/node_modules/workshopper-exercise/exercise.js:152:18)
    at /home/roman/frontend/workshop/do-it-yourself-workshop/node_modules/workshopper-exercise/exercise.js:159:7
    at failExercise (/home/roman/frontend/workshop/do-it-yourself-workshop/exercises/генерация_заготовки_проекта/exercise.js:19:9)
    at /home/roman/frontend/workshop/do-it-yourself-workshop/exercises/генерация_заготовки_проекта/exercise.js:33:24
    at FSReqWrap.oncomplete (fs.js:95:15)

Заметил, что при выборе у меня отсутствует bemhtml при выборе. Не по помогают движения Up и Down  с помощью клавиатуры.

**Comment by tavriaforever** [comment]
Жека глянь что там случилось @sipayRT

**Comment by sipayRT** [comment]
@mathetes привет
Для начала - проверь название твоего сгенеренного проекта. Оно должно быть `bfs-stub`.
Насчет 
> Just found a .yo-rc.json in a parent directory. 

Это `yo`-конфиг, его можно/нужно удалить
