### ISSUE TITLE
enb vendor.js, borschik?

### ISSUE THREAD

**Issue by pavelpower** [bem/bem-forum-content-ru#511]
Стоит задача - обернуть вендорный js в ymodules.

При этом, это должно быть технологией. Т.к. вендорный JS используется не только для самого приложения, но и в тестах. 
В общем применение банальной нотации борщика в исходнике не подходит - нужен промежуточное состояние.

Нужно из `?.vendor.js` превратить в `?.js`.

Внутри `?.vendor.js`

Будет что-то типа такого:

```javascript
(function(name, ctx, define) {
    var module = define.call(ctx, ctx);
    typeof modules === 'object'?
        modules.define(name, function(provide) { provide(module); }) :
        (ctx[name] = module);
}('backbone', this, function(global) {
    /*vendorof:../../../libs/backbone/backbone.js*/;
    return global.Backbone;
}));

modules.define('backbone', function (provide, Backbone) {
    'use strict';

    Backbone.prototype.someMethod = replaceMethod;
    provide(Backbone.noConflict());
});
```

Все текущие примеры собирают код в конечный продукт. Мне же нужен промежуточный `?.js` который будет содержать в себе код вендора.

А уже потом собираться с остальным js.

**Comment by Guria** [comment]
Можно сделать обработку борщиком на промежуточном этапе до конкатенации с другими js.

**Comment by pavelpower** [comment]
Подумал подумал, решил, что есть еще один способ.

Папку с данными блоками сделать бандлами и натравив стандартную сборку с борщиком.

А после уже результат забирать при билде другого бандла.

**Comment by pavelpower** [comment]
Где ошибка?

```javascript
 config.nodes('app/common-vendors.blocks/*', function (nodeConfig) {
        nodeConfig.addTechs([
            [levels, {
                levels: [{path: config.resolvePath('app/common-vendors.blocks'), check: true}]
            }],
            [provide, {target: '?.bemdecl.js'}]
            [deps],
            [files, {
                depsFile: '?.bemdecl.js',
                depsFormat: 'bemdecl.js',
                filesTarget: '?.base.files',
                dirsTarget: '?.base.dirs'
            }],
            [files],
            [borschikJs, {
                sourceTarget: '?.vendor.js',
                destTarget: '?.js'
            }]
        ]);

        nodeConfig.addTargets(['?.js']);
    });
```


```bash
TypeError: Cannot call method 'init' of undefined
    at /usr/local/lib/node_modules/enb/lib/node.js:350:31
    at Array.map (native)
    at module.exports.inherit.loadTechs (/usr/local/lib/node_modules/enb/lib/node.js:346:36)
    at /usr/local/lib/node_modules/enb/lib/make.js:342:33
    at Array.0 (/usr/local/lib/node_modules/enb/node_modules/vow/lib/vow.js:202:56)
    at Object.callFns [as _onImmediate] (/usr/local/lib/node_modules/enb/node_modules/vow/lib/vow.js:462:35)
    at processImmediate [as _immediateCallback] (timers.js:345:15)

```

**Comment by pavelpower** [comment]
Запятая после `[provide, {target: '?.bemdecl.js'}]`

**Comment by pavelpower** [comment]
Одно понять не могу, почему невозможно использовать `enb-borschik` без `enb-js` технологии.

**Comment by pavelpower** [comment]
В общем, борщик работает совсем под другим API, и по этому его сложно заставить хорошо работать под ENB. Написал свою технологию для подмены `include`.

**Comment by Guria** [comment]
cc @blond на всякий случай

**Comment by tadatuta** [comment]
@pavelpower если у тебя все получилось и ты доволен, то ура :)

Если же осталось желание упростить схему, то распиши подробнее, что у тебя на входе на файловой системе и что ожидается на выходе. Я пока не понимаю, почему тесты влияют на сборку в данном случае.

**Comment by blond** [comment]
> Одно понять не могу, почему невозможно использовать enb-borschik без enb-js технологии.

Не очень понял как связаны `enb-borschik` и `enb-js`?

> В общем, борщик работает совсем под другим API, и по этому его сложно заставить хорошо работать под ENB.

Как API влияет на использование в ENB?

**Comment by blond** [comment]
@pavelpower почему `js-borschik-include` не подошла?

**Comment by pavelpower** [comment]
@tadatuta - попробую рассказать на пальцах

Впиливал я unit-Тестирование на основе enb-bem-spec - пришлось его переписать, т.к. не подходит под наш way с шаблонизтором BH и Less. А времени на задачу мало.

Вендорные библиотеки сначала собирали отдельно в файл `?.lib.js`, но как оказалось для unit-тестирования не нужны все либы, и хорошо бы их матчить на отдельные блоки, да и к тому-же нужно собирать их заранее, так же по отдельным фалам. 

Самое очевидное что пришло в голову это модификация из `?.vendor.js` в обычный `?.js` прям в блоке вендора.

Т.е. создаем `?.vendor.js` там прописываем:

**common-vendors.blocks/modules/modules.vendor.js**
```javascript
/*borschik:include:../../../node_modules/ym/ym.js*/
```

**common-vendors.blocks/some-lib/some-lib.vendor.js**
```javascript
/*borschik:include:../../../node_modules/some-lib/some-lib.js*/

modules.define('some-lib', function (provide) {
    var SomeLIb = window.some_lib;

    SomeLIb.prototype.toString = function () { return this.name + ' ' + this.version; }
    provide(SomeLIb);
    delete  window.some_lib;
});
```

А дальше в добавляем ноды сборки на этот уровень переопредления:

```javascript
 config.nodes('common-vendors.blocks/*', function (nodeConfig) {
        nodeConfig.addTechs([
            [levels, {
                levels: [{path: config.resolvePath('common-vendors.blocks'), check: true}]
            }],
            [provide, {target: '?.bemdecl.js'}],
            [files, {depsFile: '?.bemdecl.js'}],
            [borschik, {source: '?.vendor.js', target: '?.js'}]
        ]);

        nodeConfig.addTargets(['?.js']);
    });
```

И ожидаем чуда. 

Не прошло. Оказывается борщик сделан совсем не так, и даже не знаю можно ли его сделать на подобии той же схемы модификации как технологии js, styl и прочие.

В общем написал свой велосипед:

**.enb/tech/vendor.js**
```javascript
var FS = require('fs'),
    PATH = require('path'),
    Vow = require('vow'),
    RGX = /\/\*vendorof:([^\*]*)\*\//gm,

    BorschikPreprocessor = require('enb-borschik/lib/borschik-preprocessor');

module.exports = require('enb/lib/build-flow').create()
    .name('vendor-js')
    .target('target', '?.js')
    .useFileList(['vendor.js'])
    .builder(function (sourceFiles) {
        var _this = this;

        return Vow.all(sourceFiles.map(function (file) {

            var path = _this.node.relativePath(file.fullname);

            if (file.name.indexOf('.vendor.js') !== -1) {

                var body = FS.readFileSync(_this.node.resolvePath(path)).toString(),
                    chunks,
                    result = '',
                    vendorCode,
                    pathList;

                while ((pathList = RGX.exec(body)) != null) {
                    try {

                        vendorCode = FS.readFileSync(_this.node.resolvePath(pathList[1])).toString();

                        chunks = body.split('/*vendorof:' + pathList[1] + '*/');

                        result = chunks[0] + '\r\n' + vendorCode + '\r\n' + chunks[1];

                    } catch (e) {
                        console.log('ERROR VENDOR::BUILD:', e.message);
                        console.log(e.stack);
                    }
                }

                return result;
            }

        }));
    })

    .createTech();
```

И теперь схема сборки вендерных либ в общую схему с y-modules у нас работает. Что позволило сократить сложность сбокри до одной команды `enb make`

Где-то на форуме встречал пост от @varya и если я верно понял, то было похожее желание делать нечто подобное.

**Comment by pavelpower** [comment]
@blond может подскажешь как с помощью борзика решить такую задачку?

Но как не курил борщик не ест файлы самостоятельно почему-то из уровня переопределения раскиданные по блокам.

Да и весь `enb-borschik` сведен к вызову `borschik.api` с прокидыванием в нее опций. 

Может я не верно курил борщик?
