### ISSUE TITLE
Валится сборка тестов.

### ISSUE THREAD

**Issue by Mellanore** [bem/bem-forum-content-ru#555]
mllnr@mllnr-osx2 ~/Desktop/rocket/rocketscan/rocketscan-vizor $ enb make specs
03:41:17.921 - build started
03:41:17.946 - [rebuild] [azaza/auth/auth.bemjson.js] file-provider
03:41:17.948 - [rebuild] [azaza/auth/auth.base.bemdecl.js] file-provider
03:41:17.953 - [rebuild] [azaza/auth/auth.levels] levels
03:41:17.955 - [rebuild] [azaza/auth/auth.base.files] files
03:41:17.955 - [rebuild] [azaza/auth/auth.base.dirs] files
03:41:17.957 - [rebuild] [azaza/auth/auth.bemjson.bemdecl.js] bemjson-to-bemdecl
03:41:17.958 - [rebuild] [azaza/auth/auth.spec-js.bemdecl.js] deps-by-tech-to-bemdecl
03:41:17.961 - [rebuild] [azaza/auth/auth.pure.spec.js] borschik-include-js
03:41:17.963 - [rebuild] [azaza/auth/auth.bemdecl.js] merge-deps
03:41:17.968 - [rebuild] [azaza/auth/auth.deps.js] deps-old
03:41:17.968 - [rebuild] [azaza/auth/auth.files] files
03:41:17.968 - [rebuild] [azaza/auth/auth.dirs] files
03:41:18.040 - [rebuild] [azaza/auth/auth.spec-js.bemhtml.bemdecl.js] deps-by-tech-to-bemdecl
03:41:18.040 - [rebuild] [azaza/auth/auth.js.bemhtml.bemdecl.js] deps-by-tech-to-bemdecl
03:41:18.042 - [rebuild] [azaza/auth/auth.css] css-stylus
03:41:18.043 - [rebuild] [azaza/auth/auth.source.browser.js] borschik-include-js
03:41:18.044 - [rebuild] [azaza/auth/auth.bemhtml.bemdecl.js] merge-bemdecl
03:41:18.046 - [rebuild] [azaza/auth/auth.bemhtml.deps.js] deps-old
03:41:18.046 - [rebuild] [azaza/auth/auth.bemhtml.files] files
03:41:18.046 - [rebuild] [azaza/auth/auth.bemhtml.dirs] files
03:41:18.056 - [rebuild] [azaza/auth/auth.browser.js] prepend-modules
03:41:18.394 - [rebuild] [azaza/auth/auth.bemhtml.js] bemhtml-old
03:41:18.396 - [rebuild] [azaza/auth/auth.html] html-from-bemjson
03:41:18.399 - [rebuild] [azaza/auth/auth.browser.bemhtml.js] bemhtml-old
03:41:18.400 - [rebuild] [azaza/auth/auth.pre.spec.js] file-merge
03:41:18.548 - [rebuild] [azaza/auth/auth.spec.js] borschik
03:41:27.107 - [spec] [azaza/auth/auth.html] 
Failed to start mocha: Init timeout
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///usr/local/lib/node_modules/enb-bem-specs/node_modules/mocha-phantomjs/lib/mocha-phantomjs.coffee. Domains, protocols and ports must match.

03:41:27.107 - build failed
03:41:27.107 - build failed
Error: specs: 1 failing
    at /usr/local/lib/node_modules/enb-bem-specs/lib/runner.js:140:31
    at Array.0 (/usr/local/lib/node_modules/enb-bem-specs/node_modules/vow/lib/vow.js:699:56)
    at Object.callFns [as _onImmediate] (/usr/local/lib/node_modules/enb-bem-specs/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:354:15)

Пол-ночи гугления не помогли( В интернетах пишут, что это баг phantomjs, но, вроде, уже пофикшеный, судя по issue в github'е. Может быть кто-нибудь сталкивался?

**Comment by zxqfox** [comment]
`file:///usr/...` — странно, что фантом прямо с диска это читает, по хорошему ему сервер надо на рандомном порте и оттуда грузить странички. Но дело, видимо, еще и в том, что фантом не успевает отрисовать страничку или поменять урл, а уже запускает тесты.

Если говорят, что пофикшено — обновления руками фантома не помогают?

**Comment by Mellanore** [comment]
Неа, версий 10 разных перепробовал :(

**Comment by zxqfox** [comment]
Позову гуру ;-)

/cc @SevInf @arikon

**Comment by arikon** [comment]
Мы с таким не сталкивались. Я бы проверил, что PhantomJS действительно последней версии (2.x), и поднимал веб-сервер для сёрва статики и тестов.

**Comment by kompolom** [comment]
@Mellanore Удалось решить проблему?

**Comment by kompolom** [comment]
@arikon Та же песня. Только начал разбираться с тестированием. Не особо понимаю где что настроить.
> и поднимал веб-сервер для сёрва статики и тестов.

можно на примере, как это сделать?
> PhantomJS действительно последней версии (2.x)

     phantomjs -v
    2.0.1-development

**Comment by tadatuta** [comment]
@kompolom а если склонировать `bem-core` или `bem-components` и запустить спеки — тоже падает?

**Comment by voischev** [comment]
А что будет если так `magic run specs`?

**Comment by kompolom** [comment]
@voischev результат тот же, но
по совету @tadatuta запустил тесты на bem-components, и.... они запустились... 
А мои нет...

**Comment by tadatuta** [comment]
> запустил тесты на bem-components, и.... они запустились...
А мои нет...

@kompolom соответственно стоит смотреть на отличия в конфигурации, версиях зависимостей и вот этом всем.

**Comment by kompolom** [comment]
@tadatuta Это понятно. Проблема в том что отличий этих очень много. И не понятно на что смотреть в первую очередь.

**Comment by kompolom** [comment]
похоже `enb-bem-specs` не использует глобально установленный phantom, а берет свой из node_modules (1.9.8) Но это, к сожалению не дает понимания почему он не запускается...

**Comment by kompolom** [comment]
@tadatuta похоже проблема связана с использованием `bh` на проекте, и отсутствием bemhtml шаблонов. Итак ситуация следующая: 
мой проект. Результат `npm i && enb make specs -n`:
````
15:30:46.423 - build started
15:30:46.627 - [rebuild] [desktop.specs/api/api.bemjson.js] file-provider
15:30:46.632 - [rebuild] [desktop.specs/api/api.base.bemdecl.js] file-provider
15:30:46.939 - [rebuild] [desktop.specs/api/api.levels] levels
15:30:46.943 - [rebuild] [desktop.specs/api/api.base.files] files
15:30:46.943 - [rebuild] [desktop.specs/api/api.base.dirs] files
15:30:46.949 - [rebuild] [desktop.specs/api/api.bemjson.bemdecl.js] bemjson-to-bemdecl
15:30:46.956 - [rebuild] [desktop.specs/api/api.spec-js.bemdecl.js] deps-by-tech-to-bemdecl
15:30:46.959 - [rebuild] [desktop.specs/api/api.pure.spec.js] js
15:30:46.961 - [rebuild] [desktop.specs/api/api.bemdecl.js] merge-deps
15:30:47.005 - [rebuild] [desktop.specs/api/api.deps.js] deps-old
15:30:47.006 - [rebuild] [desktop.specs/api/api.files] files
15:30:47.006 - [rebuild] [desktop.specs/api/api.dirs] files
15:30:47.156 - [rebuild] [desktop.specs/api/api.js.bemhtml.bemdecl.js] deps-by-tech-to-bemdecl
15:30:47.156 - [rebuild] [desktop.specs/api/api.spec-js.bemhtml.bemdecl.js] deps-by-tech-to-bemdecl
15:30:47.156 - [rebuild] [desktop.specs/api/api.source.browser.js] borschik-include-js
15:30:47.158 - [rebuild] [desktop.specs/api/api.css] css-stylus
15:30:47.179 - [rebuild] [desktop.specs/api/api.bemhtml.bemdecl.js] merge-bemdecl
15:30:47.225 - [rebuild] [desktop.specs/api/api.bemhtml.deps.js] deps-old
15:30:47.226 - [rebuild] [desktop.specs/api/api.browser.js] prepend-modules
15:30:47.227 - [rebuild] [desktop.specs/api/api.bemhtml.files] files
15:30:47.228 - [rebuild] [desktop.specs/api/api.bemhtml.dirs] files
15:30:47.926 - [rebuild] [desktop.specs/api/api.bemhtml.js] bemhtml-old
15:30:47.930 - [failed] [desktop.specs/api/api.html] html-from-bemjson
15:30:47.942 - build failed
15:30:47.944 - build failed
Error: Match failed, no templates found
    at applyc (/home/jenik/projects/blog/bem-view/desktop.specs/api/api.bemhtml.js:39:11)
    at Object.apply (/home/jenik/projects/blog/bem-view/desktop.specs/api/api.bemhtml.js:15:16)
    at /home/jenik/projects/blog/bem-view/node_modules/enb-bem-specs/node_modules/enb-bemxjst/techs/html-from-bemjson.js:40:48
    at Array.0 (/home/jenik/projects/blog/bem-view/node_modules/enb/node_modules/vow/lib/vow.js:202:56)
    at Object.callFns [as _onImmediate] (/home/jenik/projects/blog/bem-view/node_modules/enb/node_modules/vow/lib/vow.js:462:35)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
````
насколько я понял, тут bemhtml ругается на то что нет шаблонов. (Или ?)

заменяем в `enb-bem-specs` btmhtml на bh
````
bemhtml = require('enb-bh/techs/bh-bundle'), //require('enb-bemxjst/techs/bemhtml-old'),
htmlFromBemjson = require('enb-bh/techs/bemjson-to-html'),//require('enb-bemxjst/techs/html-from-bemjson'),
````
запускаем сборку:

````
15:37:20.058 - build started
15:37:20.193 - [rebuild] [desktop.specs/api/api.bemjson.js] file-provider
15:37:20.196 - [rebuild] [desktop.specs/api/api.base.bemdecl.js] file-provider
15:37:20.414 - [rebuild] [desktop.specs/api/api.levels] levels
15:37:20.417 - [rebuild] [desktop.specs/api/api.base.files] files
15:37:20.417 - [rebuild] [desktop.specs/api/api.base.dirs] files
15:37:20.422 - [rebuild] [desktop.specs/api/api.bemjson.bemdecl.js] bemjson-to-bemdecl
15:37:20.425 - [rebuild] [desktop.specs/api/api.spec-js.bemdecl.js] deps-by-tech-to-bemdecl
15:37:20.430 - [rebuild] [desktop.specs/api/api.pure.spec.js] js
15:37:20.431 - [rebuild] [desktop.specs/api/api.bemdecl.js] merge-deps
15:37:20.464 - [rebuild] [desktop.specs/api/api.deps.js] deps-old
15:37:20.465 - [rebuild] [desktop.specs/api/api.files] files
15:37:20.465 - [rebuild] [desktop.specs/api/api.dirs] files
15:37:20.648 - [rebuild] [desktop.specs/api/api.spec-js.bemhtml.bemdecl.js] deps-by-tech-to-bemdecl
15:37:20.648 - [rebuild] [desktop.specs/api/api.js.bemhtml.bemdecl.js] deps-by-tech-to-bemdecl
15:37:20.649 - [rebuild] [desktop.specs/api/api.css] css-stylus
15:37:20.650 - [rebuild] [desktop.specs/api/api.source.browser.js] borschik-include-js
15:37:20.666 - [rebuild] [desktop.specs/api/api.bemhtml.bemdecl.js] merge-bemdecl
15:37:20.673 - [rebuild] [desktop.specs/api/api.bh.js] bh-bundle
15:37:20.675 - [rebuild] [desktop.specs/api/api.bemhtml.deps.js] deps-old
15:37:20.676 - [rebuild] [desktop.specs/api/api.bemhtml.files] files
15:37:20.676 - [rebuild] [desktop.specs/api/api.bemhtml.dirs] files
15:37:20.679 - [rebuild] [desktop.specs/api/api.browser.js] prepend-modules
15:37:20.714 - [rebuild] [desktop.specs/api/api.html] bemjson-to-html
15:37:20.723 - [rebuild] [desktop.specs/api/api.browser.bemhtml.js] bh-bundle
15:37:20.727 - [rebuild] [desktop.specs/api/api.pre.spec.js] file-merge
15:37:21.048 - [rebuild] [desktop.specs/api/api.spec.js] borschik
15:37:28.045 - [spec] [desktop.specs/api/api.html] 
Failed to start mocha: Init timeout
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///home/jenik/projects/blog/bem-view/node_modules/enb-bem-specs/node_modules/mocha-phantomjs/lib/mocha-phantomjs.coffee. Domains, protocols and ports must match.


15:37:28.049 - build failed
15:37:28.049 - build failed
Error: specs: 1 failing
    at /home/jenik/projects/blog/bem-view/node_modules/enb-bem-specs/lib/runner.js:168:31
    at Array.0 (/home/jenik/projects/blog/bem-view/node_modules/vow/lib/vow.js:711:56)
    at Object.callFns [as _onImmediate] (/home/jenik/projects/blog/bem-view/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
````
Похоже есть связь с #470  
Извиняюсь за неотесаность, но я так и не понял как в этой ситуации поможет мимикрия bh...

**Comment by kompolom** [comment]
А можно тесты в браузере запустить, без phantomjs?

**Comment by rmbaad** [comment]
Словил такую же, когда забыл в конце теста вызвать provide()
