### ISSUE TITLE
Проблемы с установкой проекты через generator-bem-stub

### ISSUE THREAD

**Issue by artixgroup** [bem/bem-forum-content-ru#581]
Всем привет.

Запускаем новый проект, все предыдущие устанавливали через generator-bem-stub в качестве сборщика использовали bem-tools, проблем не было.
Сегодня пытаемся установить и встретились с проблемой такого характера:

TypeError: undefined is not a function
   at module.exports.require.create.name.target.methods._compileBEMXJST (E:\Server\Makeup\branch2\node_modules\enb-bemxjst\techs\bem-xjst.js:122:35)
   at Array.<anonymous> (E:\Server\Makeup\branch2\node_modules\enb-bemxjst\node_modules\vow\lib\vow.js:711:39)
   at Immediate.callFns [as _onImmediate] (E:\Server\Makeup\branch2\node_modules\enb-bemxjst\node_modules\vow\lib\vow.js:23:35)
   at processImmediate [as _immediateCallback] (timers.js:367:17)

**Comment by blond** [comment]
Привет! Похоже, что версия пакета `enb` ниже, чем `0.16.0`.

Какой командой запускается сборка?

/сс @tadatuta Как реализован фоллбэк для ENB в `bem-tools`? Кажется, что нужно обновить тут https://github.com/bem/bem-tools/blob/support/0.10.x/package.json#L41

**Comment by artixgroup** [comment]
Запускаю командой bem server и получаю вышеуказанную проблему.
$ bem server
15:37:36.702 - info: bem 0.10.0
15:37:36.709 - info: Trying to use ENB
Server started at http://0.0.0.0:8080
15:37:39.956 - [rebuild] [desktop.bundles\index\index.html - \desktop.bundles\index\index.bemjson.js] file-provider
15:37:40.006 - [rebuild] [desktop.bundles\index\index.html - \desktop.bundles\index\index.levels] levels
15:37:40.011 - [rebuild] [desktop.bundles\index\index.html - \desktop.bundles\index\index.bemdecl.js] bemjson-to-bemdecl
15:37:40.037 - [rebuild] [desktop.bundles\index\index.html - \desktop.bundles\index\index.deps.js] deps
15:37:40.041 - [rebuild] [desktop.bundles\index\index.html - \desktop.bundles\index\index.files] files
15:37:40.042 - [rebuild] [desktop.bundles\index\index.html - \desktop.bundles\index\index.dirs] files
15:37:40.055 - [failed] [desktop.bundles\index\index.html - \desktop.bundles\index\index.bemhtml.js] bemhtml
15:37:40.056 - [failed] [desktop.bundles\index\index.html - \desktop.bundles\index\index.html] bemjson-to-html

В файла package.json "enb": "^0.15.0". 
Запускаю все предыдущие проекты они отлично работают.

Проблема решилась запуском проекта через npm start.

Огромное спасибо!!!

**Comment by tadatuta** [comment]
Запаблишил [bem-tools@0.10.1](https://github.com/bem/bem-tools/releases/tag/v0.10.1) с `enb@0.17.2` на борту.

**Comment by zxqfox** [comment]
Может пора семвер?

**Comment by artixgroup** [comment]
tadatuta, спасибо!!!
После обновления вроде все работает!

**Comment by tadatuta** [comment]
@zxqfox пока рано — семвер начнется с 2.0.0 и честных модулей

**Comment by tadatuta** [comment]
@artixgroup ура! спасибо за репорт.

**Comment by vithar** [comment]
@tadatuta если 1.0.0 не было, то можно 1.0.0 вместо 2.0.0. ;)

**Comment by tadatuta** [comment]
@vithar была `1.0.0-alpha7`, не вижу смысла экономить чиселку

**Comment by vithar** [comment]
@tadatuta alpha же не была выпущена, в ней может что угодно измениться до релиза. Я за выпуск 1.0.0, когда и если он будет.

**Comment by zxqfox** [comment]
Соглашусь с @vithar, ничего страшного, если -alpha и -beta имеют 10% общего кода ;-). Такое бывает.

**Comment by tadatuta** [comment]
я и за 10% бы не поручился ;)
но 1.0.0, так 1.0.0, хотя и не понимаю, зачем экономить числа, вряд ли мы в longint (или что там поддерживается?) упремся.

**Comment by zxqfox** [comment]
От тюрмы, сумы и лонгинта не зарекайся ;-)

**Comment by blond** [comment]
2.0.0 всегда выглядит лучше, чем 1.0.0 ;)

**Comment by vithar** [comment]
Если 1.0.0 не было, сразу делается 2.0.0 — для меня ЭТО выглядит странно.

**Comment by zxqfox** [comment]
Че к чему нашли о чем спорить. Делаем 1.0.0-beta да и все.

Вообще, я бы согласился с @tadatuta если бы дошло бы до 1.0.0-rc, но там даже не beta...

**Comment by tadatuta** [comment]
@vithar @zxqfox node.js@0.12 -> node.js@4.0 ;)

**Comment by zxqfox** [comment]
@tadatuta Т.е. ты за 4.0.0? ;-)
