### ISSUE TITLE
Ошибка при переходе на localhost

### ISSUE THREAD

**Issue by DbImOK85** [bem/bem-forum-content-ru#628]
Добрый день! При запуске bem server и переходе по ссылке http://0.0.0.0:8080 выдает ошибку

17:21:43.279 - [rebuild] [desktop.bundles/index/index.bemjson.js] file-provider
17:21:43.307 - [failed] [desktop.bundles/index/index.levels] levels
17:21:43.308 - [failed] [desktop.bundles/index/index.files] files
17:21:43.308 - [failed] [desktop.bundles/index/index.deps.js] deps
17:21:43.308 - [failed] [desktop.bundles/index/index.bemhtml.files] files
17:21:43.308 - [failed] [desktop.bundles/index/index.bemhtml.deps.js] deps
17:21:43.309 - [failed] [desktop.bundles/index/index.bemhtml.bemdecl.js] deps-by-tech-to-bemdecl
17:21:43.309 - [failed] [desktop.bundles/index/index.bemhtml.js] bemhtml
17:21:43.309 - [failed] [desktop.bundles/index/index.css] stylus
17:21:43.309 - [failed] [desktop.bundles/index/index.browser.js] browser-js
17:21:43.309 - [failed] [desktop.bundles/index/index.browser.bemhtml.js] bemhtml
17:21:43.311 - [rebuild] [desktop.bundles/index/index.bemdecl.js] bemjson-to-bemdecl
17:21:43.312 - [failed] [desktop.bundles/index/index.html] bemjson-to-html
17:21:43.312 - [failed] [desktop.bundles/index/index.min.css] borschik
17:21:43.312 - [failed] [desktop.bundles/index/index.pre.js] file-merge
17:21:43.313 - [failed] [desktop.bundles/index/index.js] prepend-modules
Error: ENOENT: no such file or directory, scandir '/home/dbimok/Документы/bem-new/libs/bem-core/common.blocks'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at module.exports.inherit.load (/home/dbimok/Документы/bem-new/node_modules/enb-bem-techs/lib/levels/level.js:212:28)
    at /home/dbimok/Документы/bem-new/node_modules/enb-bem-techs/techs/levels.js:110:38
    at Array.map (native)
    at /home/dbimok/Документы/bem-new/node_modules/enb-bem-techs/techs/levels.js:109:42
    at Array.<anonymous> (/home/dbimok/Документы/bem-new/node_modules/enb/node_modules/vow/lib/vow.js:202:56)
    at Immediate.callFns [as _onImmediate] (/home/dbimok/Документы/bem-new/node_modules/enb/node_modules/vow/lib/vow.js:462:35)
    at processImmediate [as _immediateCallback] (timers.js:374:17)

В чем может быть проблема?

**Comment by tadatuta** [comment]
Добрый!

Судя по всему не была установлена (или установлена неправильно) библиотека `bem-core`.
Стоит попробовать выполнить `bower install`.

**Comment by DbImOK85** [comment]
Спасибо за ответ! Не корректно стал bem-core. Сервер запустился.)
