### ISSUE TITLE
Настройка bem-grid

### ISSUE THREAD

**Issue by FA73F0X** [bem/bem-forum-content-ru#633]
Здравствуйте!
Нужна помощь по настройке bem-grid. Делаю все как написано здесь https://github.com/bem-incubator/bem-grid Но в результате стилей в браузере нет. `enb make` отрабатывает без ошибок. Я понимаю, что дело в настройке, но информацию по этой теме найти не могу. 
На форуме подобная тема есть. В конце отписались, что заработало а что сделали ни слова. Если есть у кого инструкция или статья по настройке, буду благодарен и думаю в дальнейшем не только я.

**Comment by tadatuta** [comment]
cc @awinogradov

**Comment by awinogradov** [comment]
@FA73F0X Рассказывай как подключаешь) Там дока старая, простите меня)

**Comment by FA73F0X** [comment]
Подключаю как написано. Если дока на сегодня не актуальна, давайте набросаем черновик новой доки здесь ) За одно и обкатаем новый вариант.  @awinogradov напиши, что установить и какие файлы подправить а я отпишусь, что у меня получилось.

**Comment by awinogradov** [comment]
А можешь прислать конфиг или ссылку на реп? Если нет, то опиши стек: препроцессор и версии библиотек. Это очень поможет!

**Comment by FA73F0X** [comment]
Да, забыл написать, если enb-postcss обязателен для работы, то с ним у меня проблема он не устанавливается. Я использую NVM для Node сейчас попрыгаю по версиям. Попробую собраться на других версиях node.  Хотя не в этом дело скорее всего.

**Comment by FA73F0X** [comment]
https://github.com/FA73F0X/bemgrid

**Comment by FA73F0X** [comment]
Linux version 3.16.0-38-generic (buildd@allspice) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #52~14.04.1-Ubuntu SMP
x86_64
node v4.1.2
npm 2.14.4

**Comment by awinogradov** [comment]
enb-postcss обязателен. Он собирает и компилирует стили. Кроме того обязателен набор плагинов из bem-grid.

**Comment by FA73F0X** [comment]
Собрался на разных версиях node и везде одна ошибка при установке пакета  enb-postcss. Все остальное ставится и работает без проблем. Сам Bem тоже без проблем работает. Как мне этот пакет ставить, если он огрызается?)

npm WARN peerDependencies The peer dependency enb@>=0.13.11 <1.0.0 included from enb-postcss will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/home/guru/.nvm/versions/node/v0.12.7/bin/node" "/home/guru/.nvm/versions/node/v0.12.7/bin/npm" "i" "--save-dev" "enb-postcss"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package enb does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer enb-postcss@0.1.2 wants enb@>=0.13.11 <1.0.0
npm ERR! peerinvalid Peer enb-bem-techs@2.1.0 wants enb@>=0.15.0 <2.0.0
npm ERR! peerinvalid Peer enb-bemxjst@2.1.0 wants enb@>= 0.16.0 < 2.0.0
npm ERR! peerinvalid Peer enb-borschik@2.1.0 wants enb@>= 0.16.0 < 2.0.0
npm ERR! peerinvalid Peer enb-js@1.1.0 wants enb@>= 0.15.0 <2.0.0
npm ERR! peerinvalid Peer enb-stylus@2.1.0 wants enb@>=0.16.0 <2.0.0

npm ERR! Please include the following file with any support request:
npm ERR!     /home/guru/projects/code/training/bem/bemg/npm-debug.log

**Comment by Guria** [comment]
в `enb-postcss` не успели добавить поддержку недавно вышедшего `enb@1.0`
Установите 0.17.2: `npm i --save-dev enb@0.17.2`

**Comment by FA73F0X** [comment]
Алексей, спасибо за подсказку. `enb-postcss` установился и `bem-grid` стоить. но стилей нет. Возможно я не все настроил? Для css какие пути нужно прописывать или достаточно прописать ? 
```
{
    block : 'row',
    content : [
        {
            elem : 'col',
            mods : { mw : 6 },
            content : 'left column'
        },
        {
            elem : 'col',
            mods : { mw : 6 },
            content : 'right column'
        }
    ]
}
```

**Comment by awinogradov** [comment]
@FA73F0X а хде [тут](https://github.com/FA73F0X/bemgrid/blob/master/.enb/make.js#L48) enb-postcss?) Смотри [чего](https://github.com/bem-incubator/bem-grid/blob/master/.enb/make.js#L32) не хватает  и [вот](https://github.com/bem-incubator/bem-grid/blob/master/.enb/postcss-plugins.js).

**Comment by FA73F0X** [comment]
@awinogradov  да его там нет `bemgrid/.enb/make.js`, но установка прошла без ошибок. А файлы  `bem-grid/.enb/make.js` и `bem-grid/.enb/postcss-plugins.js` у меня установились в папку `libs` в корне.

**Comment by awinogradov** [comment]
Эти файлы и плагины должны участвовать в твоей сборке. Перенеси их в свой конфиг и подключи по примеру с бем-грид. Все заработает.

**Comment by FA73F0X** [comment]
Не понимаю, что мешает разработчикам  Bem  добавить Grid в ядро. А то получаются какие-то костыли и протезы в данном случае. Я делая проект в Meteor устанавливаю сетку одной командой. А в Bem не один плагин нужно поставить, исправить кучу файлов и не забыть переместить папки в другую директорию. Да, чуть не забыл еще нужно откатиться а то плагин еще не обновился для новой версии enb. 
Извините, но такой инструмент только усложняет процесс разработки!
Можете закрыть тему.

**Comment by c1n1k** [comment]
реально жопа какая-та с установкой, попробовал по иструкции, вылезла ошибка попробовал ещё раз вылезла npm WARN EPEERINVALID vow-queue@0.0.2 requires a peer of vow@~0.3.9 but none was installed.

**Comment by awinogradov** [comment]
Возьми ветку из project-stub с именем bem-grid. Там все работает. Можно сделать диф от мастера чтобы увидеть как. Скоро появится нормальная инструкция и примеры в репозитории bem-grid. Потерпите немножко:)

**Comment by c1n1k** [comment]
не ставится она

**Comment by awinogradov** [comment]
Кто она? Будет продуктивнее, если подробнее опишешь проблему и что делаешь.

**Comment by c1n1k** [comment]
пробовла установить ветку  git clone https://github.com/bem/project-stub.git --depth 1 --branch bem-grid
получил https://gist.github.com/c1n1k/0bc3b24e030d3d662968

**Comment by apsavin** [comment]
Я не имею отношения к bem-grid, но:

1. Скорее всего, с пятой нодой и npm 3 вообще ничего не выйдет. Попробуйте 4-ую.
2. Вывод `Please try running this command again as root/Administrator.` как бы намекает, что стоит попробовать поставить от рута.

**Comment by c1n1k** [comment]
это как? у меня win10

**Comment by tadatuta** [comment]
@awinogradov Антон, есть какой-нибудь эстимейт по улучшению ситуации с bem-grid?

**Comment by awinogradov** [comment]
@tadatuta давай к концу недели пофикшу все

**Comment by voischev** [comment]
@tadatuta все будет ;)

**Comment by awinogradov** [comment]
Теперь есть и релиз. Со скомпиленным css и enb модулем https://github.com/bem-incubator/bem-grid/releases/tag/2.2.0

**Comment by koloskof** [comment]
@awinogradow как можно отрубить адаптивность сетки?

**Comment by awinogradov** [comment]
Не думаю, что я правильно понял вопрос:) можешь рассказать чего хочется?

**Comment by koloskof** [comment]
Хочу чтоб у контейнера оставался min-width: 1100px (допустим) и колонки не перестраивались при ресайзе окна. Сейчас мне нужна сетка, только для десктопной версии. Прописать gridMinWidth : '1100px' не пракатило )

**Comment by awinogradov** [comment]
Братишка, так тебе надо у твоего контейнера установить min-width: 1100px, и внутри него использовать сетку с колонками s размерности: {s: true} - для автоматического расчета ширины, {sw: 0..12} - для ручного управления ;) Размерность s задаёт работу на маленьких девайсах и выше, так что ничего не будет переустраиваться.

**Comment by koloskof** [comment]
Вот как оно тут оказывается. Это тебе не буЦтраповский грид ) Спасибо, Антон. Разобрался.

**Comment by adinvadim** [comment]
Установил bem-grid как enb модуль, а он конфликует со stylus, как быть?

**Comment by awinogradov** [comment]
Опиши подробнее что значит конфликтует?

**Comment by adinvadim** [comment]
Подключил bem-grid как enb module

Вот лог
```
Error: Concurrent techs for target: index.css, techs: "stylus" vs "enb-bem-grid"
    at Error (native)
    at module.exports.inherit._registerTarget (/Users/adinvadim/sandbox/_liot.mipt/vps/frontend/themes/basic/node_modules/enb/lib/node/node.js:396:19)
    at /Users/adinvadim/sandbox/_liot.mipt/vps/frontend/themes/basic/node_modules/enb/lib/node/node.js:523:23
    at Array.forEach (native)
    at /Users/adinvadim/sandbox/_liot.mipt/vps/frontend/themes/basic/node_modules/enb/lib/node/node.js:522:31
    at Array.map (native)
    at module.exports.inherit._registerTargets (/Users/adinvadim/sandbox/_liot.mipt/vps/frontend/themes/basic/node_modules/enb/lib/node/node.js:521:21)
    at module.exports.inherit.requireSources (/Users/adinvadim/sandbox/_liot.mipt/vps/frontend/themes/basic/node_modules/enb/lib/node/node.js:470:14)
    at module.exports.inherit.build (/Users/adinvadim/sandbox/_liot.mipt/vps/frontend/themes/basic/node_modules/enb/lib/node/node.js:572:21)
    at /Users/adinvadim/sandbox/_liot.mipt/vps/frontend/themes/basic/node_modules/enb/lib/make.js:482:54
```
Вот настройки
```
            [techs.stylus, {
                target: '?.css',
                autoprefixer: {
                    browsers: ['ie >= 10', 'last 2 versions', 'opera 12.1', '> 2%']
                },
                sourceSuffixes: ['styl', 'css', 'post.css'],
                useNib: true,
            }],

            [require('bem-grid').enb, {
                sourceSuffixes: ['post.css'],
                config : {
                    maxWidth : '900px',
                    gutter : '10px',
                    flex : 'flex'
                }
            }],
```

**Comment by awinogradov** [comment]
@adinvadim а зачем ты в stylus postcss отдаешь? :) тут проблема в настройке enb. Тебе надо результат stylus передавать в сетку;)

**Comment by belozyorcev** [comment]
Ребят. Уже весь вечер промучался с установкой `shraps` (bem-grid). Сборка зависает на `21:07:52.891 - [rebuild] [desktop.bundles/index/index.min.js] borschik`
`. Файла css после технологии shraps.enb не создаётся. Кто-то сталкивался с данной проблемой?

**Comment by DjonyBastone** [comment]
Сборка Gulp. gulpfile - <script src="https://gist.github.com/DjonyBastone/4302ff39b7c2ace02bcdbd447ca91562.js"></script>

выдает ошибку при сборке:

[14:58:45] Starting 'default'...
[14:58:45] Starting 'build'...
[14:58:46] gulp-debug: desktop.bundles\index\index.bemhtml.js
[14:58:46] gulp-debug: desktop.bundles\index\index.html
{ [Error: CSS parse error index.min.css: Identifier is expected
   18 |            align-items: stretch;
   19 |}
   20 |@media (--xxlarge-only) {
----------------^
   21 |    .header {
   22 |        width: 100%;]
  message: 'CSS parse error index.min.css: Identifier is expected\n   18 |            align-items: stretch;\n   19 |}\n   20 |@media (--xxlarge-only) {\n----------------^\n   21 |    .header {\n   22 |        width: 100%;',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-csso',
  __safety: { toString: [Function: bound ] } }
[14:58:46] gulp-debug: desktop.bundles\index\index.min.js
[14:58:46] The following tasks did not complete: default, build
[14:58:46] Did you forget to signal async completion?

Пожалуйста помогите разобраться

**Comment by DjonyBastone** [comment]
@media (--xxlarge-only) {
    .header {
        width: 100%;
    }
}

Или не правильно css написал?

**Comment by tadatuta** [comment]
Судя по логу, дело именно в ошибке в синтаксисе стилей, сборка не виновата.

**Comment by DjonyBastone** [comment]
const postcss = require('gulp-postcss');
const sharps = require('sharps').postcss;
postcss([sharps({
    columns: 12, // default
    maxWidth: '2048px',
    gutter: '10px',
    flex: 'flex'
})]);
В настройке указано что максимальная ширина 2048px.
С этими настройками, выплывает ошибка при попытке стилизации блока .header:

@media (--xxlarge-only) {
    .header {
        width: 100%;
    }
}

Сделано в точности по примеру из документации - https://github.com/theprotein/sharps/blob/master/common.blocks/mq/mq.ru.md

- Цель: задать при помощи  Media queries максимальную ширину 2048рх., не используя row  и col

Если не сложно можете выложить пример применения Media queries для модульной сетки Sharps ?

Или подскажите в каком месте я не прав?

**Comment by tadatuta** [comment]
в комменты призывается @awinogradov

**Comment by belozer** [comment]
@DjonyBastone а что за ошибка?

**Comment by awinogradov** [comment]
Плюсую предыдущему дяде, больше подробностей бы или тест кейс очень помогли бы.

**Comment by tadatuta** [comment]
если я правильно понял, то текст ошибки в предпредыдущем сообщении @DjonyBastone

**Comment by DjonyBastone** [comment]
Не появляются колонки вообще, sharps - не работает. Думаю что с ошибкой написал gulpfile.js

Кроме этого при сборке выскакивает ошибка. Все что связано с ошибкой выложил в - https://gist.github.com/DjonyBastone/ee11a069c13023944279d8430317cf7a

Проект с ошибкой целиком - https://github.com/DjonyBastone/osipbove-bem-project.git

**Comment by awinogradov** [comment]
@DjonyBastone может тебе просто не хватает https://github.com/theprotein/sharps/blob/master/engines/plugins.js#L9 ? Просто потому что для [декларации media](https://github.com/theprotein/sharps/blob/master/common.blocks/mq/mq.post.css) используется этот плагин.

**Comment by DjonyBastone** [comment]
@awinogradov, благодарю))) 

А пример gulpfile.js с настроеным sharps можете скинуть?

**Comment by awinogradov** [comment]
@DjonyBastone не могу) я не пользуюсь гульпом. Но кажется, что дело не в нем. PostCSS настраивается одинаково для всех плагинов. Можно смотреть любой пример хоть [тут](https://github.com/postcss/postcss#gulp). А что значит не работают row и col?

**Comment by DjonyBastone** [comment]
Блок row,  2 элемента col по 6 колонок

В css ни чего по ним не приходит.  Следовательно сборка css плагина sharps не происходит. Скорее всего, не верно в конфиге  сборщика что-то.

**Comment by awinogradov** [comment]
Судя по всему [это](https://github.com/DjonyBastone/osipbove-bem-project/blob/master/gulpfile.js#L7) должно быть [здесь](https://github.com/DjonyBastone/osipbove-bem-project/blob/master/gulpfile.js#L61). Sharps работает как обычный плагин для PostCSS и подключается так же.

**Comment by DjonyBastone** [comment]
Да этот вариант я попробовал уже. С таким вариантом лог:

"C:\Program Files (x86)\JetBrains\PhpStorm 2016.3\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" E:\html\osipbove-bem-project\node_modules\gulp\bin\gulp.js --color --gulpfile E:\html\osipbove-bem-project\gulpfile.js default
[14:10:21] Using gulpfile E:\html\osipbove-bem-project\gulpfile.js
[14:10:21] Starting 'default'...
[14:10:21] Starting 'build'...
TypeError: require(...) is not a function
    at css (E:\html\osipbove-bem-project\gulpfile.js:56:42)
    at tryCatch (E:\html\osipbove-bem-project\node_modules\gulp-bem-bundle-builder\lib\index.js:93:47)
    at tryCatch (E:\html\osipbove-bem-project\node_modules\gulp-bem-bundle-builder\lib\index.js:137:16)
    at Object.keys.map.target (E:\html\osipbove-bem-project\node_modules\gulp-bem-bundle-builder\lib\index.js:93:32)
    at Array.map (native)
    at DestroyableTransform._transform (E:\html\osipbove-bem-project\node_modules\gulp-bem-bundle-builder\lib\index.js:91:40)
    at DestroyableTransform.Transform._read (E:\html\osipbove-bem-project\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (E:\html\osipbove-bem-project\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (E:\html\osipbove-bem-project\node_modules\readable-stream\lib\_stream_writable.js:347:64)
    at writeOrBuffer (E:\html\osipbove-bem-project\node_modules\readable-stream\lib\_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (E:\html\osipbove-bem-project\node_modules\readable-stream\lib\_stream_writable.js:274:11)
    at Readable.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Readable.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Readable.push (_stream_readable.js:134:10)
[14:10:22] gulp-debug: desktop.bundles\index\index.bemhtml.js
[14:10:22] gulp-debug: desktop.bundles\index\index.html
[14:10:22] gulp-debug: desktop.bundles\index\index.min.js
[14:10:22] The following tasks did not complete: default, build
[14:10:22] Did you forget to signal async completion?

Process finished with exit code 0

**Comment by awinogradov** [comment]
Ну не знаю) У меня такая же нога и не болит) https://github.com/theprotein/sharps/blob/master/.enb/make.js

**Comment by DjonyBastone** [comment]
gulpfile теперь содержит такую внутренность:

css: bundle =>
                bundle.src('css')
                    .pipe(stylus())
                    .pipe(require('gulp-one-of')())
                    .pipe(postcss([
                        require('postcss-import')(),
                        require('postcss-each'),
                        require('postcss-for'),
                        require('postcss-simple-vars')(),
                        require('postcss-calc')(),
                        require('postcss-nested'),
                        require('rebem-css'),
                        require('sharps')({ columns: 12, maxWidth: '2048px', gutter: '10px', flex: 'flex' }),
                        require('postcss-url')({ url: 'inline' }),
                        require('autoprefixer')(),
                        require('postcss-reporter')()
                    ]))
                    .pipe(concat(bundle.name + '.min.css'))
                    .pipe(csso()),

С такой настройкой выдает лог как - в моем предыдущем сообщении.

Из лога я понял что-то с map и target.

Кто нибудь с помощью gulp пробовал собирать css с Sharps ???

**Comment by awinogradov** [comment]
Выглядит так что sharps тут не причем. Пришли лог, непонятно же ничего.

**Comment by DjonyBastone** [comment]
E:\html\osipbove-bem-project\gulpfile.js default
[15:31:45] Using gulpfile E:\html\osipbove-bem-project\gulpfile.js
[15:31:45] Starting 'default'...
[15:31:45] Starting 'build'...
TypeError: require(...) is not a function
    at css (E:\html\osipbove-bem-project\gulpfile.js:58:42)
    at tryCatch (E:\html\osipbove-bem-project\node_modules\gulp-bem-bundle-builder\lib\index.js:93:47)
    at tryCatch (E:\html\osipbove-bem-project\node_modules\gulp-bem-bundle-builder\lib\index.js:137:16)
    at Object.keys.map.target (E:\html\osipbove-bem-project\node_modules\gulp-bem-bundle-builder\lib\index.js:93:32)
    at Array.map (native)
    at DestroyableTransform._transform (E:\html\osipbove-bem-project\node_modules\gulp-bem-bundle-builder\lib\index.js:91:40)
    at DestroyableTransform.Transform._read (E:\html\osipbove-bem-project\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (E:\html\osipbove-bem-project\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (E:\html\osipbove-bem-project\node_modules\readable-stream\lib\_stream_writable.js:347:64)
    at writeOrBuffer (E:\html\osipbove-bem-project\node_modules\readable-stream\lib\_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (E:\html\osipbove-bem-project\node_modules\readable-stream\lib\_stream_writable.js:274:11)
    at Readable.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Readable.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Readable.push (_stream_readable.js:134:10)
[15:31:46] gulp-debug: desktop.bundles\index\index.bemhtml.js
[15:31:46] gulp-debug: desktop.bundles\index\index.html
[15:31:47] gulp-debug: desktop.bundles\index\index.min.js
[15:31:47] The following tasks did not complete: default, build
[15:31:47] Did you forget to signal async completion?

Process finished with exit code 0

**Comment by DjonyBastone** [comment]
https://github.com/DjonyBastone/osipbove-bem-project.git

Здесь лежит проект в том состоянии в котором вылазит ошибка

**Comment by belozer** [comment]
@awinogradov при отключении sharps из списка ошибка require пропадает.

**Comment by belozer** [comment]
@awinogradov хотя разобрался с проблемой

@DjonyBastone 
не require

```js
require('sharps')({ columns: 12, maxWidth: '2048px', gutter: '10px',   flex: 'flex' }),
```
а 
```js
sharps({ columns: 12, maxWidth: '2048px', gutter: '10px',   flex: 'flex' }),
// или
require('sharps').postcss({ columns: 12, maxWidth: '2048px', gutter: '10px',   flex: 'flex' }),
```

ты ведь вначале файла правильно объявил sharps
```js
const sharps = require('sharps').postcss;
```

**Comment by DjonyBastone** [comment]
Алиллуя!!! ЗАРАБОТАЛО

@belozer спасибо

**Comment by DjonyBastone** [comment]
Sharps подключился. Собирает все медиа и классы которые есть в Sharps, т.е. не выборочно по наличию классов row и col. CSSO не вычищает - не используемые классы и @media, и в CSS попадает более 24000 строк.

1) Media queries не работает при следующих стилях:
@media (--xxlarge-only) {
    .header {
        width: 50%;
    }
}
То есть при сборке нет ни --xxlarge-only, ни .header { width: 50%; }, блок: header - существует
- Правильно ли задан класс?
- Должно ли собираться по этим данным вообще? И что должно собраться?  Подразумевалось, что для данного диапазона экранов, header будет иметь ширину 50%

2) Проводят ли оптимизацию CSS после применения Sharps ? Какими инструментами это производится? (CSSO не вычищает)
