### ISSUE TITLE
Непонятно в каком месте кода ошибка

### ISSUE THREAD

**Issue by nut707** [bem/bem-forum-content-ru#643]
Пока делаю первое тестовое задание и сразу возникает вопрос. Как понять в каком месте кода возникает ошибка? Из того, что выдает страничка, мне сложно сделать какие-то выводы.

Собственно сообщение об ошибке:

SyntaxError: Unexpected token {
   at exports.runInThisContext (vm.js:53:16)
   at Module._compile (module.js:413:25)
   at Object.Module._extensions..js (module.js:452:10)
   at Module.load (module.js:355:32)
   at Function.Module._load (module.js:310:12)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)
   at doRequire (C:\Users\nut707\Desktop\test-project\node_modules\enb-bem-techs\node_modules\enb-async-require\lib\async-require.js:23:30)
   at C:\Users\nut707\Desktop\test-project\node_modules\enb-bem-techs\node_modules\enb-async-require\lib\async-require.js:35:9
   at Object.Promise (C:\Users\nut707\Desktop\test-project\node_modules\enb-bem-techs\node_modules\vow\lib\vow.js:308:9)

**Comment by tadatuta** [comment]
Ошибка где-то в BEMJSON. Пропущена какая-нибудь запятая или скобка.

**Comment by nut707** [comment]
ну это понятно, а как узнать в каком точно месте? может есть какие то сторонние средства позволяющие это отследить?

**Comment by zxqfox** [comment]
jslint/jshint file.bemjson.js
