### ISSUE TITLE
Почему не подключаются css из папок элементов?

### ISSUE THREAD

**Issue by mathetes** [bem/bem-forum-content-ru#732]
В двух блоках наблюдается проблема отсутствия css свойств именно для элементов блоков
Вот структура файлов и папок

```
header
     __nameplate
          header__nameplate.styl
     header.styl
```
Свойства header.styl подключаются, а из header__nameplate.styl нет

**Comment by tadatuta** [comment]
Предположу, что нет зависимости от элемента в deps.js

**Comment by mathetes** [comment]
Где и как правильно подключить зависимости? Куда прописать header__nameplate?
Сейчас в header.deps.js такой скрипт.
```
({
    shouldDeps: [
        'logo', 'control-group',
        {
        block: 'input',
        mods: {
            theme: 'islands',
            size: 'm',
            type: 'search'
        }
	    },
	    {
	        block: 'button',
	        mods: {
	            theme: 'islands',
	            size: 'm'
	        }
	    }
    ]
})
```

**Comment by tadatuta** [comment]
Если `nameplate` — это обязательный элемент, который он всегда присутствует у блока `header`, то его можно добавить прямо в зависимости `header`:
```js
({
    shouldDeps: [
        elems: ['nameplate'], // вот так
        'logo', 'control-group',
        {
            block: 'input',
            mods: {
                theme: 'islands',
                size: 'm',
                type: 'search'
            }
        },
        {
            block: 'button',
            mods: {
                theme: 'islands',
                size: 'm'
            }
        }
    ]
})
```

**Comment by mathetes** [comment]
Добавил как советовали. В итоге ошибка
Error: Syntax error in file "/home/roman/allApps/01_BEM/biblelinks/common.blocks/header/header.deps.js": 

Unexpected token ,
   at /home/roman/allApps/01_BEM/biblelinks/node_modules/enb-bem-techs/lib/deps/deps-resolver.js:222:31
   at Array.<anonymous> (/home/roman/allApps/01_BEM/biblelinks/node_modules/vow/lib/vow.js:711:56)
   at Immediate.callFns [as _onImmediate] (/home/roman/allApps/01_BEM/biblelinks/node_modules/vow/lib/vow.js:23:35)
   at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by tadatuta** [comment]
это я потерял скобки, отредактировал свой предыдущий комментарий

**Comment by mathetes** [comment]
@tadatuta Спасибо, заработало.
Как выложить скриншот на форуме?

**Comment by tadatuta** [comment]
Опубликовать картинку на любом удобном хостинге картинок (например, на Яндекс.Диск ;)) и дальше как обычно в маркдауне: `![alt](http://my-site.ru/example.png)`
