### ISSUE TITLE
Bag or Feature?

### ISSUE THREAD

**Issue by pavelpower** [bem/bem-forum-content-ru#844]
Разбирая рекомендации от @blond в pull-request: https://github.com/enb-make/enb/pull/426

Переделал технологию `write-file` и поменял тест.
Тест сделал с проверкой контента в файле и он отвалился!

Реализовал небольшой проектик, в общем провел такой путь: https://github.com/enb-make/enb/pull/426#issuecomment-177334190

И действительно, получи в контенте файла `undefined` вместо переданного мной контента.

Поставил `console.trace(args);` https://github.com/dfilatov/vow-fs/blob/master/lib/fs.js#L28

Вот, что он выдал:

```bash
 enb make

Trace: [ '~/Projects/opensource/test-enb/.enb/tmp',
  undefined,
  [Function] ]
    at ~/Projects/opensource/test-enb/node_modules/vow-fs/lib/fs.js:28:25
    at ~/Projects/opensource/test-enb/node_modules/vow-fs/lib/fs.js:316:24
    at Array.<anonymous> (~/Projects/opensource/test-enb/node_modules/vow/lib/vow.js:712:56)
    at Immediate.callFns [as _onImmediate] (~/Projects/opensource/test-enb/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
Trace: [ '~/Projects/opensource/test-enb/.enb/tmp',
  [Function] ]
    at Object.stat (~/Projects/opensource/test-enb/node_modules/vow-fs/lib/fs.js:28:25)
    at Object.module.exports.isDir (~/Projects/opensource/test-enb/node_modules/vow-fs/lib/fs.js:234:21)
    at onFailed (~/Projects/opensource/test-enb/node_modules/vow-fs/lib/fs.js:307:28)
    at Array.<anonymous> (~/Projects/opensource/test-enb/node_modules/vow/lib/vow.js:712:56)
    at Immediate.callFns [as _onImmediate] (~/Projects/opensource/test-enb/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
03:09:57.177 - build started
Trace: [ '~/Projects/opensource/test-enb/bundle',
  undefined,
  [Function] ]
    at ~/Projects/opensource/test-enb/node_modules/vow-fs/lib/fs.js:28:25
    at ~/Projects/opensource/test-enb/node_modules/vow-fs/lib/fs.js:316:24
    at Array.<anonymous> (~/Projects/opensource/test-enb/node_modules/vow/lib/vow.js:712:56)
    at Immediate.callFns [as _onImmediate] (~/Projects/opensource/test-enb/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
Trace: [ '~/Projects/opensource/test-enb/bundle',
  [Function] ]
    at Object.stat (~/Projects/opensource/test-enb/node_modules/vow-fs/lib/fs.js:28:25)
    at Object.module.exports.isDir (~/Projects/opensource/test-enb/node_modules/vow-fs/lib/fs.js:234:21)
    at onFailed (~/Projects/opensource/test-enb/node_modules/vow-fs/lib/fs.js:307:28)
    at Array.<anonymous> (~/Projects/opensource/test-enb/node_modules/vow/lib/vow.js:712:56)
    at Immediate.callFns [as _onImmediate] (~/Projects/opensource/test-enb/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

// called builder in techs/write-file.js

Trace: [ '~/Projects/opensource/test-enb/bundle/bundle.md',
  '## Test \n this a test text',
  { encoding: 'utf8' },
  [Function] ]
    at Object.<anonymous> (~/Projects/opensource/test-enb/node_modules/vow-fs/lib/fs.js:28:25)
    at ~/Projects/opensource/test-enb/node_modules/vow-fs/lib/fs.js:46:35
    at Object.vow.invoke (~/Projects/opensource/test-enb/node_modules/vow/lib/vow.js:1050:20)
    at Object.Queue._runTask (~/Projects/opensource/test-enb/node_modules/vow-queue/lib/queue.js:204:27)
    at Object.Queue._run (~/Projects/opensource/test-enb/node_modules/vow-queue/lib/queue.js:186:18)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
03:09:57.201 - [rebuild] [bundle/bundle.md] write-file
Trace: [ '~/Projects/opensource/test-enb/bundle/bundle.md',
  'undefined',
  'utf8',
  [Function] ]
    at Object.<anonymous> (~/Projects/opensource/test-enb/node_modules/vow-fs/lib/fs.js:28:25)
    at ~/Projects/opensource/test-enb/node_modules/vow-fs/lib/fs.js:46:35
    at Object.vow.invoke (~/Projects/opensource/test-enb/node_modules/vow/lib/vow.js:1050:20)
    at Object.Queue._runTask (~/Projects/opensource/test-enb/node_modules/vow-queue/lib/queue.js:204:27)
    at Object.Queue._run (~/Projects/opensource/test-enb/node_modules/vow-queue/lib/queue.js:186:18)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
03:09:57.206 - build finished - 38ms
```

Так вот и вопрос, это баг или фича гонять по два раза?

Может я чего не так использую?

**Comment by pavelpower** [comment]
Заметьте что каждый раз еще меняется и контент!
