### ISSUE TITLE
Помогите пожалуйста найти ошибку

### ISSUE THREAD

**Issue by rustam-mh** [bem/bem-forum-content-ru#870]
var fs = require('fs'),
              path = require('path'),
              vm = require('vm'),
              vow = require('vow');

        var Bundle = function(name, folder){
	        this.name = name+'.bundles';
	        this.folder = folder;	
	        this.path = path.join(this.name,this.folder,this.folder);
	        this.BEMTREE = this.bemtree();
	        this.BEMHTML = require('../../../' + this.path + '.bemhtml.js');
        };

        Bundle.prototype.bemtree = function(){
	         var bemtreePath = './' + this.path + '.bemtree.js',
	         bemtreeFile = fs.readFileSync(bemtreePath, 'utf-8'),
	         context = vm.createContext({
		        console: console,
	    	        Vow: vow,
	    	        require: require,
		        setImmediate: setImmediate	    	
	        });

	        vm.runInContext(bemtreeFile, context);
	        return context.BEMTREE;
        };
        module.exports = Bundle;

        var Bundle = require('../server/libs/bem');
        var index = new Bundle('desktop', 'index');
  
        index.BEMTREE.apply({ block: 'header' }).then(function(bemjson){
	        console.log(bemjson);
        });

evalmachine.<anonymous>:1823
    throw new Error(msg || 'Assertion failed');
    ^

Error: Wrong .match() argument
    at assert (evalmachine.<anonymous>:1823:11)
    at Tree.match (evalmachine.<anonymous>:1613:5)
    at Object.<anonymous> (evalmachine.<anonymous>:1967:1)
    at Tree.build (evalmachine.<anonymous>:1517:13)
    at BEMHTML.compile (evalmachine.<anonymous>:372:18)
    at buildBemXjst (evalmachine.<anonymous>:1844:5)
    at evalmachine.<anonymous>:2080:15
    at evalmachine.<anonymous>:2083:3
    at Object.exports.runInContext (vm.js:44:17)
    at Bundle.bemtree (/home/rustam/www/rhblog/server/libs/bem/index.js:24:5)

**Comment by zxqfox** [comment]
в каком-то из шаблонов в .match не функция?

**Comment by tadatuta** [comment]
Не обязательно в `match()`, может быть в любой из «сахарных» функций (`tag()`, `attrs()` и т.д.).

Могу помочь найти точное места, если опубликуешь собранный бандл и входные данные.

**Comment by rustam-mh** [comment]
index.bemjson.js:

        `module.exports = {block : 'header'};`

bundle.js:    

>            var fs = require('fs');
>            var path = require('path');
>            var vm = require('vm');
>            var vow = require('vow');
> 
>            var Bundle = function(name, folder){
> 	           this.name = name+'.bundles';
> 	           this.folder = folder;	
> 	           this.path = path.join(this.name,this.folder,this.folder);
> 	           this.BEMTREE = this.bemtree();
> 	           this.BEMHTML = require('../../../' + this.path + '.bemhtml.js');
>             };
> 
>             Bundle.prototype.bemtree = function(){
> 	               var bemtreePath = './' + this.path + '.bemtree.js',
> 	               bemtreeFile = fs.readFileSync(bemtreePath, 'utf-8'),
> 	               context = vm.createContext({
>                             console: console,
> 	    	               Vow: vow,
> 	    	               require: require,
> 		               setImmediate: setImmediate	    	
> 	                });
>        	        vm.runInContext(bemtreeFile, context);
> 	                return context.BEMTREE;
>              };
>              module.exports = Bundle;

test.js:
                var Bundle = require('../server/libs/bem');
                var index = new Bundle('desktop', 'index');
                index.BEMTREE.apply({ block: 'header' }).then(function(bemjson){
                          console.log( index.BEMHTML.apply(bemjson) );
                });

**Comment by tadatuta** [comment]
я про `/home/rustam/my-bem-project/desktop.bundles/index/index.bemtree.js` говорил
